### PR TITLE
Suggest API

### PR DESCRIPTION
**Pull request by rishsingh07**
Added suggest API in contacts form.

### CODE REVIEW

**Comment by sagararyal** [comment]
@rishsingh07 can you clean up console logs, and also implement this for signup page and edit profile as well?

**Comment by norbertschuler** [comment]
- [ ] I recognized the suggestions showing an address + zip + city + country, but we are not using the country. Is it possible to limit the suggestion to the chosen country?

**Comment by norbertschuler** [comment]
- [ ] Suggestions are not supporting dark mode:

Bildschirmfoto 2021-09-04 um 17 03 18

**Review by norbertschuler — APPROVED** [review]
LGFM

**Pull request merged**
