### PR TITLE
Displays new project properties (map/project details)

### PR DESCRIPTION
**Pull request by mohitb35**
**Project Details**
1. Renames "First Tree Planted" to "Restoration Started", "Planting Seasons" to "Restoration Seasons"
2. Displays Main Interventions (if data exists)
3. Also makes changes to allow restoration/activity seasons to occupy full column width.
4. Shows ecosystem for the project
5. Shows per unit cost based on `unitType` instead of project `purpose`
6. Shows unit type for total units donated (instead of "Trees" by default).

**Map (List and Popup on hover)**
1. Shows ecosystem for the project
2. Shows per unit cost based on `unitType` instead of project `purpose`
3. Shows unit type for total units donated (instead of "Trees" by default).

**Create/Edit Project (Detailed Analysis)**
1. Changes label from "First Tree Planted" to "Restoration Started"

Screenshot 2023-08-03 at 10 54 05 AM
Screenshot 2023-08-03 at 10 52 40 AM
Screenshot 2023-08-03 at 10 52 34 AM
Screenshot 2023-08-03 at 10 51 13 AM
Screenshot 2023-08-03 at 10 54 25 AM
Screenshot 2023-08-03 at 10 54 20 AM

Pending
- [ ] Showing total donations / units > API change may be needed, and corresponding front end changes as well

### CODE REVIEW

**Comment by mariahosfeld** [comment]
Functionality looks good in the PR.

**Comment by norbertschuler** [comment]
@mohitb35 Found a `ECOSYSTEMTYPES.UNDEFINED` value on the profile page, e.g. https://planet-webapp-jeyqh5q72-planetapp.vercel.app/t/saving-the-amazon

Bildschirmfoto 2023-08-19 um 10 53 59

**Comment by norbertschuler** [comment]
> @mohitb35 Found a `ECOSYSTEMTYPES.UNDEFINED` value on the profile page, e.g. https://planet-webapp-jeyqh5q72-planetapp.vercel.app/t/saving-the-amazon

Another example https://planet-webapp-jeyqh5q72-planetapp.vercel.app/t/saving-nature on staging where I also wondered by the currency for the last project is displayed in $ for m^2 while the others are shown in € for trees (the currency I had chosen)?

Bildschirmfoto 2023-08-19 um 11 02 57

**Comment by mohitb35** [comment]
> @mohitb35 Found a `ECOSYSTEMTYPES.UNDEFINED` value on the profile page, e.g. https://planet-webapp-jeyqh5q72-planetapp.vercel.app/t/saving-the-amazon
> 
> Bildschirmfoto 2023-08-19 um 10 53 59

Resolved here - 97accaf

**Comment by mohitb35** [comment]
> > @mohitb35 Found a `ECOSYSTEMTYPES.UNDEFINED` value on the profile page, e.g. https://planet-webapp-jeyqh5q72-planetapp.vercel.app/t/saving-the-amazon
> 
> Another example https://planet-webapp-jeyqh5q72-planetapp.vercel.app/t/saving-nature on staging where I wondered why the currency for the last project is displayed in $ for m^2 while the others are shown in € for trees (the currency I had chosen)? But this wrong amount and currency are only on the profile page - for the list or on https://planet-webapp-jeyqh5q72-planetapp.vercel.app/saving-sumatra?site=site_alPHGosr3p0SZnf it is shown correctly in €.
> 
> Bildschirmfoto 2023-08-19 um 11 02 57

There seems to be an inconsistency in the API response.

**Review by prachigarg19 — APPROVED** [review]

**Pull request merged**
