### PR TITLE
support safe-area-inset-top

### PR DESCRIPTION
**Pull request by norbertschuler**
Fix #1562

The web application is not checking for safe areas yet and unfortunately is using a lot of fixed and absolute positions for elements, so using it as a bookmarked application or PWA or embedded in a native app wrapper using fullscreen does not work on devices having a notch:

Bildschirmfoto 2022-08-28 um 13 02 18Bildschirmfoto 2022-08-28 um 13 01 57

Changes in this pull request:
- added support of the `env(safe-area-inset-top)` for some components, e.g. Navigation and Map et al
- #1562 is also included here

TODO:
- test all components

### CODE REVIEW

**Comment by norbertschuler** [comment]
from Sagar: Shadow from the menu bar can be removed to make the transition seamless

**Comment by prachigarg19** [comment]
@norbertschuler This problem has still not been solved in this PR. I'm not sure if we are still looking for a solution for the same.
https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1562#pullrequestreview-1096254040
image

**Comment by norbertschuler** [comment]
> @norbertschuler This problem has still not been solved in this PR. I'm not sure if we are still looking for a solution for the same. [#1562 (review)](https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1562#pullrequestreview-1096254040) 

Right, I never got an answer in the linked comment. Either we get a new design for this dialog (which I am sorry I cannot do) to support smaller screens or we do not support smaller screen and ignore it for now.

**Comment by mohitb35** [comment]
@norbertschuler The code looks fine to me. I didn't see the issue while checking out the present app on an Android device after installing the live webapp as a PWA - the notch did not obstruct the app.

**Review by mohitb35 — COMMENTED** [review]
@norbertschuler The code looks fine to me. However, I didn't see the issue while checking out the live app on an Android device after installing as a PWA - the notch did not obstruct the app.

**Comment by norbertschuler** [comment]
> @norbertschuler The code looks fine to me. However, I didn't see the issue while checking out the live app on an Android device after installing as a PWA - the notch did not obstruct the app.

I assume this is only important for iOS. I have no real Android device with a notch. If testing this on a simulator, I only get a bigger header for the Android app, and also on a Huawei P30 on Browserstack it is part of the navigation bar:

Screenshot_20221008_133509Bildschirmfoto 2022-10-08 um 13 40 06

**Comment by norbertschuler** [comment]
@mariahosfeld can you give me some feedback if you are still interested in this PR and if it part of your roadmap?

**Comment by mohitb35** [comment]
@norbertschuler code looks good. Noticed a minor bug while scrolling - the content is visible above the title bar (above the notch above safe area view)

File

File (1)

**Comment by norbertschuler** [comment]
> @norbertschuler code looks good. Noticed a minor bug while scrolling - the content is visible above the title bar (above the notch above safe area view)

Well, I know about that and accepted that as a feature instead of a bug as I even liked it this way ;-) But that's a business decision.

**Comment by norbertschuler** [comment]
It does not make sense to keep this any more if it is not wanted.

**Pull request closed without merging**
