### PR TITLE
added language switcher on map page near attribution

### LINKED ISSUE #375: Language Switcher in Map Attribution
**Describe the feature you'd like to see included in Plant-for-the-Planet Web App.**
image

Exact Content: `🌐 English · USD`

Use of emoji is fine, SVG can be used as well.

**What are the use cases for this feature?**
change the language on donate page

Replicate the behavior of the following button:

Screen Shot 2020-11-05 at 11 11 49 AM

**Examples of this feature or functionality.**
language switcher is present on about/leaderboard pages

This component should load.
Screen Shot 2020-11-05 at 11 12 02 AM

### PR DESCRIPTION
**Pull request by sarveshpro**
Fixes #375 

image

### CODE REVIEW

**Review by norbertschuler — CHANGES_REQUESTED** [review]
Switching language works for me, source code looking good, but please add some spacing between currency and privacy policy link:

Bildschirmfoto 2020-11-13 um 09 18 36

**Comment by sagararyal** [comment]
This is not a good practice.

- [ ] Responsiveness is broken

- [ ] When mapboxgl adds more attribution the text ends up behind the attribution text [check single project where satellite layer is loaded]

- [ ] On Click Effects!!!

**Comment by sagararyal** [comment]
@sarveshpro can you try this out?

Screen Shot 2020-11-15 at 4 34 31 PM

**Comment by sarveshpro** [comment]
and what about mobile and tablet screens? attribution goes behind the project list.

**Pull request merged**
