### PR TITLE
enable login on salesforce tenant

### PR DESCRIPTION
**Pull request by sarveshpro**
To do - 

- [ ] merge to develop
- [ ] merge to tenant/salesforce
- [ ] deploy trees.salesforce.com from tenant/salesforce

### CODE REVIEW

**Comment by norbertschuler** [comment]
The following stuff will still have the Plant-for-the-Planet wording & branding:
- Auth0 mail templates
- Backend mail templates

**Comment by sagararyal** [comment]
@norbertschuler that's fine.

**Comment by norbertschuler** [comment]
> * [ ]  merge to develop
> * [ ]  merge to tenant/salesforce
> * [ ]  deploy trees.salesforce.com from tenant/salesforce

@sarveshpro we do not have a branch `tenant/salesforce` anymore. Salesforce tenant is currently deployed from our main branch. So maybe this list is not feasible.

**Review by norbertschuler — APPROVED** [review]
I tested it locally by changing my `.env.local` to use all the production systems and temporarily added http://localhost:3000 to the allowed Callback URL for the Auth0 application of Salesforce. I tested successfully: 
- Login / Logout
- Profile view / profile change / target change
- Create widget
- Donation using profile address (I did not do a real donation!)

**Comment by sarveshpro** [comment]
Merging this to develop but **DO NOT DELETE** this branch. Manually deploying trees.salesforce.com using this branch.

**Pull request merged**
