### PR TITLE
fix the zoom issue for project site

### PR DESCRIPTION
**Pull request by sunilsabatp**
1. debugged  zoom issue for the project site
go to `/project `by selecting any one project from the landing page

## Summary by CodeRabbit

- **Refactor**
	- Enhanced the Project maps interface by utilizing more efficient React hooks, improving interaction with plant locations and project sites.
- **Chores**
	- Cleaned up unnecessary code in the map zoom functionality.

### CODE REVIEW

**Comment by norbertschuler** [comment]
Zooming seems to work. 

Not sure if this is connected with this fix or generally broken in the latest code base of multi tenancy vs. https://www1.plant-for-the-planet.org, but we currently cannot link to any projects site other but the default one using deep links e.g. https://planet-webapp-multi-tenancy-setup-git-hotfix-z-28f9f2-planetapp.vercel.app/de/yucatan?site=site_cIS3reMZ5v1yvDw - you will always be redirected to https://planet-webapp-multi-tenancy-setup-git-hotfix-z-28f9f2-planetapp.vercel.app/de/yucatan?site=site_ybVo0Vn007jQl56. Also deep links to treemapper areas e.g. https://planet-webapp-multi-tenancy-setup-git-hotfix-z-28f9f2-planetapp.vercel.app/de/yucatan?ploc=LKB5P9 won't work and will be redirected to the default site.

**Review by mariahosfeld — CHANGES_REQUESTED** [review]
Tested using an incognito window. Selecting Yucatan from the list resulted in an initial start to zoom in then the page was stuck.
On another project this also happened, upon selecting a third project, it finally worked, and subsequent loads of the first projects as well. Should not happen, zooming should work right away, maybe slowly because of the data amount, but not get stuck.

**Comment by norbertschuler** [comment]
Will we still continue this PR or abandon it?

**Comment by mohitb35** [comment]
Closed as addressed by #2082

**Pull request closed without merging**
