### PR TITLE
fix: restrict api call loop

### PR DESCRIPTION
**Pull request by sunilsabatp**
visit to -> ` /yucatan?ploc=RM0TJZ `and change locale to DE 
issue -> api call loop (see the network tab once  a specific plant location get selected)
get more insight ->https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1618#issuecomment-1328576565  
also visit the comment to get demo of the issue ->https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1618#issuecomment-1328033009

### CODE REVIEW

**Comment by sagararyal** [comment]
#### 📝 Changed routes:


| [**/\[p\]**](https://planet-webapp-3obn5vh3e-planetapp.vercel.app/[p]) | [**/**](https://planet-webapp-3obn5vh3e-planetapp.vercel.app/) |
|:-:|:-:|
|<a href="https://planet-webapp-3obn5vh3e-planetapp.vercel.app/[p]">Screenshot of /[p]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/qoy6xLz2T69xpr8alfH5r3SVPob5pzxlN-yXF1AvA1QlqM-E1sRzbbLY3IpQnJMN1_oYhzrnxUAEgvS0AMBFsA.png">(view full size)</a> |<a href="https://planet-webapp-3obn5vh3e-planetapp.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/qNHnoRbaLRJvU8cMO3unAjvGl-jW8-bCA1XobWV1iUlHghc8sVQ2LtDnEMdtShY41kiZDI6BOKIgtutGc7tXFQ.png">(view full size)</a> |







Commit f4e38d0b5036367eb4c26ad40838bc87105eac93 (https://planet-webapp-3obn5vh3e-planetapp.vercel.app).

**Review by norbertschuler — DISMISSED** [review]
If not wanting to merge this directly into #1618, let's merge it into develop and then merge develop into #1618.

**Comment by mohitb35** [comment]
@sunilsabatp The language switching on the project details (/p]) page does not update the project language any more.

**Review by mohitb35 — CHANGES_REQUESTED** [review]
@sunilsabatp The language switching on the project details (/p]) page does not update the project language any more.

**Comment by mariahosfeld** [comment]
No longer needed, therefore closing it.

**Pull request closed without merging**
