### PR TITLE
Landing Video: use video.js

### PR DESCRIPTION
**Pull request by sarveshpro**
- [ ] video not autoplaying on iphone

### CODE REVIEW

**Comment by norbertschuler** [comment]
I just tested dev.pp.eco on my iPhone X with Safari and latest iOS. The intro video automatically starts to play. Which device does not play it?

**Comment by sarveshpro** [comment]
develop also works on my device, doesn't work on @sagararyal and @harshvitra devices. Safari mostly. There's another PR - #1173

**Comment by norbertschuler** [comment]
- This pull request version is not autoplaying on my device (iPhone X with latest iOS).
- The version from #1173 is looping on my device.
- Version from dev.pp.eco is working fine on my device.

**Comment by harshvitra** [comment]
> * Version from dev.pp.eco is working fine on my device.

The dev.pp.eco doesn't work for me
Screenshot 2021-08-16 at 3 35 48 PM

**Pull request closed without merging**
