### PR TITLE
Embbedable donations

### PR DESCRIPTION
**Pull request by sarveshpro**
Use iframe directly because widget is causing styling issue

### CODE REVIEW

**Comment by sagararyal** [comment]
#### 📝 Changed routes:


| [**/**](https://planet-webapp-rhrrhpn8f-planetapp.vercel.app/) |
|:-:|
|<a href="https://planet-webapp-rhrrhpn8f-planetapp.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/h9pSVvPNZdtvFaS3v3p9ubASdDmN-KolML3hWL92XjDTs9ODftGDPWrLiBAQTFZKLmWP3oPao0DRfoS27koH6A.png">(view full size)</a> |







Commit dd60b6abb281a31b42c46f68245494e8056f4828 (https://planet-webapp-rhrrhpn8f-planetapp.vercel.app).

**Comment by norbertschuler** [comment]
- [ ] Clicking donate from the project popup on the map still opens the old donation dialog (probably this is custom code instead of using the same component everywhere a project is shown which is not the best architecture):

Bildschirmfoto 2021-12-10 um 08 19 28

**Comment by norbertschuler** [comment]
- [ ] Latest deployment does not open anymore on my iPhone with Safari. The version before still had been showing the donation dialog:

image

**Comment by norbertschuler** [comment]
Will this be abandoned in favor of #1363?

**Pull request closed without merging**
