### PR TITLE
feat: allow czech language for selective tenants

### PR DESCRIPTION
**Pull request by sunilsabatp**
new language ('Czech')

### CODE REVIEW

**Comment by mariahosfeld** [comment]
Functionality of this works, release after coordination with the neccessary translations.

**Review by mohitb35 — APPROVED** [review]
Code looks good.

**Comment by norbertschuler** [comment]
The translation status for czech language is not yet very well for planet-webapp at https://translate.lingohub.com/plant-for-the-planet/dashboard/planet-webapp/ (much better - but not perfect - for planet-donation at https://translate.lingohub.com/plant-for-the-planet/dashboard/planet-donations/).

**Comment by mohitb35** [comment]
Blocked for release until czech translation status is at an acceptable state.

**Pull request merged**
