### PR TITLE
fixed local storage bug

### LINKED ISSUE #833: TypeError: Cannot read property 'getItem' of null
If the browser cannot get items from local storage, can we set default values for language/currency?

Login would def not work, but that should be fine.

Sentry Issue: [APP-20-NEXT-15T](https://sentry.io/organizations/plant-for-the-planet/issues/2184837800/?referrer=github_integration)

```
TypeError: Cannot read property 'getItem' of null
  at call (./src/utils/storeConfig.ts:4:33)
  at new Promise (<anonymous>)
  at storeConfig (./src/utils/storeConfig.ts:3:1)
  at h (./pages/_app.tsx:68:5)
  at doRender (../../client/index.tsx:521:7)
...
(22 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by rishsingh07**
fixed #833

### CODE REVIEW

**Review by norbertschuler — COMMENTED** [review]
This is an improvement for this special case, but we should write an abstraction for use localStorage in general everywhere in our codebase to avoid such errors. Compare #712

**Comment by harshvitra** [comment]
> This is an improvement for this special case, but we should write an abstraction for use localStorage in general everywhere in our codebase to avoid such errors. Compare #712

I'm working on this, meanwhile this can be merged

**Review by norbertschuler — APPROVED** [review]
Code formatting could be nicer (use some tool?), but looks good for me.

**Comment by harshvitra** [comment]
> Code formatting could be nicer (use some tool?), but looks good for me.

@rishsingh07 for next time

**Pull request merged**
