### PR TITLE
fix: prevents crash redeeming codes without tpo

### PR DESCRIPTION
**Pull request by mohitb35**
Fixes crash seen while redeeming codes when tpos array is empty (during code validation phase)

Also fixes crash when a 500 error is received while converting codes to trees.

### CODE REVIEW

**Comment by sagararyal** [comment]
#### 📝 Changed routes:


| [**/claim/\[type\]/\[code\]**](https://planet-webapp-184pge5qt-planetapp.vercel.app/claim/[type]/[code]) |
|:-:|
|<a href="https://planet-webapp-184pge5qt-planetapp.vercel.app/claim/[type]/[code]">Screenshot of /claim/[type]/[code]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/0-PhDlpR2w-QjpF4nkmenURDtSYv1lQINanluEUbbLuSzEAih3lCit0Wwnr7tIsr8odSVPl9epnipfYcVQZC7A.png">(view full size)</a> |







Commit 66876c41a2d0b08fa291c8c0bb0702d830af98f8 (https://planet-webapp-184pge5qt-planetapp.vercel.app).

**Review by Shreyaschorge — APPROVED** [review]

**Review by norbertschuler — COMMENTED** [review]
Code looks good. Do you have a TPO returning an empty array for which we can test this or do I have to create my own for testing this?

**Comment by mohitb35** [comment]
When you generate generic bulk codes, and use the codes from the downloaded csv file (after clicking on Download Codes), you should get back an empty tpos array in the API response while redeeming any of the codes.

Regards
Mohit
________________________________

**Comment by norbertschuler** [comment]
> When you generate generic bulk codes, and use the codes from the downloaded csv file (after clicking on Download Codes), you should get back an empty tpos array in the API response while redeeming any of the codes.

I just tested with this PR, generated some bulk codes and tried to redeem the first one in my own profile and got some data in the TPO array in the API reply - maybe the API got fixed meanwhile?

Bildschirmfoto 2022-07-30 um 11 40 35

**Comment by mohitb35** [comment]
> > When you generate generic bulk codes, and use the codes from the downloaded csv file (after clicking on Download Codes), you should get back an empty tpos array in the API response while redeeming any of the codes.
> 
> I just tested with this PR, generated some bulk codes and tried to redeem the first one in my own profile and got some data in the TPO array in the API reply - maybe the API got fixed meanwhile?
> 
> Bildschirmfoto 2022-07-30 um 11 40 35

Yes I think that's been fixed. 

The codes that were earlier returning an empty TPO array also seem to be working. Also, the /convertCode API that was earlier returning a 500 status is working now.

**Comment by norbertschuler** [comment]
> Yes I think that's been fixed.
> 
> The codes that were earlier returning an empty TPO array also seem to be working. Also, the `/convertCode` API that was earlier returning a 500 status is working now.

We should merge this anyway as it makes the frontend code more robust against future problems.

**Pull request merged**
