### PR TITLE
Added leaderboard page on /all route for planet tenant

### LINKED ISSUE #184: Create Leaderboard Page
Page should be divided into components.
Design: https://xd.adobe.com/view/8f1c5110-4d7d-445d-8283-8eb1674ce2e4-da4f/screen/9a8b67c7-38f7-420f-921b-df282c6ce486/

First component: Forest Frontrunners 
if tenant ≠ planet this page won't appear.

Second Component: Donations [do not build now]

Third Component: Info Cards

Forth Component: SNL Video
Please show this video in countries where the video is not restricted.
Youtube blacklist: https://api.unblockvideos.com/youtube_restrictions?id=9V981RXcmH8&pretty_print=true

If county in local storage matches county in the blacklist do not show the video component.

### PR DESCRIPTION
**Pull request by harshvitra**
Fixes #184 

Added leaderboard page on /all route for planet tenant

Sections added - 
1. Leaderboard scores
2. Statistics
3. Articles

### CODE REVIEW

**Review by Plant-for-the-Planet — CHANGES_REQUESTED** [review]
Please adjust the components to responsive breakpoints;

Enable all supported languages
pass x-session-id in api

TODO: @jmiridis 
– Implement global leaderboard API
– Implement stats API

**Comment by sagararyal** [comment]
```

Failed to compile.
--
15:57:38.730 | ModuleNotFoundError: Module not found: Error: Can't resolve 'react-js-pull-to-refresh' in '/vercel/workpath0/pages'
15:57:38.730 | > Build error occurred
15:57:38.731 | Error: > Build failed because of webpack errors
15:57:38.731 | at build (/vercel/workpath0/node_modules/next/dist/build/index.js:15:918)
15:57:38.731 | at runMicrotasks (<anonymous>)
15:57:38.731 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
15:57:38.743 | npm ERR! code ELIFECYCLE
15:57:38.743 | npm ERR! errno 1
15:57:38.744 | npm ERR! planet-web2@0.1.0 build: `next build`
15:57:38.744 | npm ERR! Exit status 1
15:57:38.745 | npm ERR!
15:57:38.745 | npm ERR! Failed at the planet-web2@0.1.0 build script.
15:57:38.745 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
15:57:38.752 | npm ERR! A complete log of this run can be found in:
15:57:38.752 | npm ERR!     /vercel/.npm/_logs/2020-11-08T14_57_38_745Z-debug.log
15:57:38.757 | Error: Command "npm run build" exited with 1

```

**Comment by harshvitra** [comment]
### **Need this Video link (youtube would be best)**

Screenshot 2020-11-10 at 11 06 18 AM

### **Need this Link**

Screenshot 2020-11-10 at 11 06 22 AM

### **Need this Link**
Screenshot 2020-11-10 at 11 06 26 AM

**Comment by harshvitra** [comment]
@sagararyal is this ready to merge?

**Comment by felixfinkbeiner** [comment]
Looks great! A few minor issues:

➔ The footer seems to be the incorrect width. It does not align with the logo in the menu bar
➔ The “how do we restore a trillion trees” and the “How do we select projects” are also not horizontally aligned correctly
➔ Delete “do” in “How do we select projects”
➔ There should be the emoji down arrow to the right of “And finally, this”

**Comment by felixfinkbeiner** [comment]
Looks great! Just a few little issues:
➔ The footer seems to be the incorrect width. It does not align with the logo in the menu bar
➔ The “how do we restore a trillion trees” and the “How do we select projects” are also not horizontally aligned correctly
➔ Delete “do” in “How do we select projects”
➔ There should be the emoji down arrow to the right of “And finally, this”

**Pull request merged**
