### PR TITLE
Update subscriptions

### PR DESCRIPTION
**Pull request by prachigarg19**
1. Omit the option to edit the date, just leave Amount and Frequency
2. When the user selects a date for the cancellation, the Frontend Client needs to calculate how many times we will still deduct the money via the selected payment method from their account. This way we want to ensure that the donor has all necessary information right away and can keep track.

### CODE REVIEW

**Comment by sagararyal** [comment]
#### 📝 Changed routes:


| [**/404**](https://planet-webapp-8r4op975o-planetapp.vercel.app/404) | [**/claim/\[type\]/\[code\]**](https://planet-webapp-8r4op975o-planetapp.vercel.app/claim/[type]/[code]) |
|:-:|:-:|
|<a href="https://planet-webapp-8r4op975o-planetapp.vercel.app/404">Screenshot of /404</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/r6NX9Qc0Sk8U3ENxcE8qkQPUSgsAaxDlLdE_gLWVlLNb05mDLVW9JcecMUYDFAtizR58X_gGVghAuNzE23Qxig.png">(view full size)</a> |<a href="https://planet-webapp-8r4op975o-planetapp.vercel.app/claim/[type]/[code]">Screenshot of /claim/[type]/[code]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/bDsA5nVbuqZ4VTnCyAgQeiqvPFYsFA9kepzCD8RcOYEM5kLc3Lj2TMMICvOHAjkLji_RhBnwWs1N7C8eOqsB8w.png">(view full size)</a> |



| [**/profile/history**](https://planet-webapp-8r4op975o-planetapp.vercel.app/profile/history) | [**/profile/impersonate-user**](https://planet-webapp-8r4op975o-planetapp.vercel.app/profile/impersonate-user) |
|:-:|:-:|
|<a href="https://planet-webapp-8r4op975o-planetapp.vercel.app/profile/history">Screenshot of /profile/history</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/7Fo7wpSsh8WquSMt7rWGobR71BvPshxBXxzC2PYf96nlCu1_y8G6B7kocUkl7Ve9sYWh6Uju5nICBvFzUJJt8g.png">(view full size)</a> |<a href="https://planet-webapp-8r4op975o-planetapp.vercel.app/profile/impersonate-user">Screenshot of /profile/impersonate-user</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ZmsJtyBbCzhkbtRaIHYXtw462teqleNYuDEJUurpAzQzwk_QTDb3Co6P-mGtMbtwwhua-OCCklbe5RePpDU47A.png">(view full size)</a> |



| [**/profile/projects/\[id\]**](https://planet-webapp-8r4op975o-planetapp.vercel.app/profile/projects/[id]) | [**/profile/recurrency**](https://planet-webapp-8r4op975o-planetapp.vercel.app/profile/recurrency) |
|:-:|:-:|
|<a href="https://planet-webapp-8r4op975o-planetapp.vercel.app/profile/projects/[id]">Screenshot of /profile/projects/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/0lkuFOY-JHnn9vFl8qDrJVvssKHlQPrhSGGQWhlqhgD5ck7BdK-u-HSgxy8IyPGb_xCD63G2XGViFGSPXkNyDQ.png">(view full size)</a> |<a href="https://planet-webapp-8r4op975o-planetapp.vercel.app/profile/recurrency">Screenshot of /profile/recurrency</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ump38cE_CBhCj2vYNvWbwNmsLjyF1OlSKpcNomWsAtRSgz7wMKNC1ut4qRcaXPeWDkRhWylFulKK0WZOqvGiVw.png">(view full size)</a> |



And 1 other route:
- [**/profile/redeem/\[code\]**](https://planet-webapp-8r4op975o-planetapp.vercel.app/profile/redeem/[code])



Commit 93bbf40806e28078688ce58caaedad98539c5724 (https://planet-webapp-8r4op975o-planetapp.vercel.app).

**Comment by norbertschuler** [comment]
As this PR is based on feature-branch `feature/expandable-info-offline-subscriptions` but has lately merged develop into it while develop has not been merged into `feature/expandable-info-offline-subscriptions` the diff now shows too much changes and it hardly reviewable.

**Comment by mariahosfeld** [comment]
Tried to test the functionality:

- [ ] When changing the amount/frequency, I am stuck on the pop-up after pressing the confirmation button. Change does not get saved. (Console shows a range error.)
- [ ] Canceling the recurrency does not work, status remains active. (though calculation when selecting a date works).

**Comment by mohitb35** [comment]
Closed as this has been moved to #1729

**Pull request closed without merging**
