### PR TITLE
Feature/fix manage projects

### LINKED ISSUE #604: Edit polygons for existing TPO project sites
**Describe the feature you'd like to see included in Plant-for-the-Planet Web App.**
Add a function to allow TPOs to edit their project sites polygons again.

**What are the use cases for this feature?**
Allow corrections to the polygon without having to delete and create the sites newly.

Screen Shot 2020-12-06 at 10 12 33 AM

### LINKED ISSUE #691: Uploading bigger reports to project fails
**Describe the bug**
I tried to upload a bigger report file (> 20MB) to my project. Within the upload process I got an error and the app is frozen in the upload process (not handling this error properly).

A file of the size 21.142.000 bytes failed to upload, two file of the size 19.201.698 bytes and 18.292.075 bytes successfully got uploaded.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to Manage Projects
2. Open a projects
3. Upload a bigger PDF as a project spending report

**Expected behavior**
Avoid or at least handle the error

**What actually happens**
App is frozen.

**Screenshots**
Bildschirmfoto 2020-12-21 um 11 15 18

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome

### PR DESCRIPTION
**Pull request by harshvitra**
- [x] Fixed button designs and media uploading with button"
- [x] Fixed file uploading and pdf text
- [x] Maximum size for files and error on rejected
- [x] Error handling for file types
- [x] isReviewed condition
- [x] Fix #604

- [x]   Clicking `Upload Photos` button triggers `Save and Continue` before image is uploaded.
Screen Shot 2021-03-07 at 3 31 51 PM

- [x] Dragging image in removes other images from view and shows the new image only.

Screen Shot 2021-03-07 at 3 34 21 PM

- [x] Align height for receive donations so screen does not get pushed up/down when enabled/disabled; and also fix the issue where the price does not show for existing projects.

Screen Shot 2021-03-07 at 3 37 36 PM

- [x] Disable Certification block, if no certificates exist for the project.
Screen Shot 2021-03-07 at 3 34 58 PM

- [x]  When creating a new project: 
If Publish Project, provide transport and Accept donations are not selected during project creation;
validation error will currently mark publish project and receive donations active.
Even though accept donations is active; donation amount is not shown.
Screen Shot 2021-03-06 at 10 45 32 PM

- [x] change text to: Changes to your project are Live

Screen Shot 2021-03-07 at 3 45 56 PM

- [x] App is setting Accept Donations true even if it is not defined.
```
{"name":"Apple Trees","slug":"apple-farming","classification":"large-scale-planting","geometry":{"type":"Point","coordinates":[-5.461908330496199,17.569130217744153]},"countTarget":500,"website":"https://apple.eco","description":"Apple Farming","acceptDonations":true,"treeCost":null,"currency":"EUR","visitorAssistance":false,"publish":false}

```

- [x] Pre center the map for project site to project coordinates.

Screen Shot 2021-03-07 at 3 36 06 PM

Fixes #691

### CODE REVIEW

**Comment by sagararyal** [comment]
- [ ]  When creating a new project: 
If Publish Project, provide transport and Accept donations are not selected during project creation;
validation error will currently mark publish project and receive donations active.
Even though accept donations is active; donation amount is not shown.
Screen Shot 2021-03-06 at 10 45 32 PM

**Comment by sagararyal** [comment]
Saving project; with the current code let to the project to be disabled for donation; as the price was cleared.

Screen Shot 2021-03-07 at 11 53 07 AM

**Comment by harshvitra** [comment]
> * [ ]  After saving the step 1.
>   two concurrent requests are made: one with scope images, one without. This can be reduced to 1 API call.
> 

They have different purposes. 
First one doesn't send images

**Comment by harshvitra** [comment]
> * [ ]  Saving project; with the current code let to the project to be disabled for donation; as the price was cleared.

This is a different flag - 
acceptDonations - is used by the TPOs to indicate us that they want to receive donations
allowDonations - is used by us after we approve the project to collect donations 

in the front we use allowDonations Flag.

**Comment by harshvitra** [comment]
> * [ ]  Saving project; with the current code let to the project to be disabled for donation; as the price was cleared.

Can't be replicated, maybe fixed

**Comment by sagararyal** [comment]
Further Bugs:

- [ ] First Tree Planted Validation Failed (2015-0-8) 
Screen Shot 2021-03-08 at 10 58 56 AM

```
{"yearAbandoned":2000,"firstTreePlanted":"2015-0-8","plantingDensity":"1100","employeesCount":"121","mainChallenge":"Our main focus for 2021 and 2022 is to increase the biodiversity of the planted tree species","motivation":"Plant-for-the-Planet has been able to acquire more than 22,500 hectares of former forest land, spread over several reforestation sites, which have been degraded for different reasons, such as deforestation, forest fires, cattle grazing or the cultivation of chili or rice in monoculture.","siteOwnerType":["private"],"siteOwnerName":"Plant-for-the-Planet Foundation","acquisitionYear":2015,"degradationYear":1980,"degradationCause":"Predominantly cattle grazing and forest fires","longTermPlan":"The main objective is the planting of 100 million trees in Yucatán, in areas degraded by deforestation. The reforested trees help to bind CO2 and - by planting exclusively indigenous trees in a mixed forest - to preserve the local ecosystem.","plantingSeasons":[6,7,8,9,10,11,12]}
```

- [ ] Adding picture still refreshes the page to show one picture only.
Screen Shot 2021-03-08 at 10 56 21 AM
Screen Shot 2021-03-08 at 10 56 52 AM

**Pull request merged**
