### PR TITLE
Project spending year issue

### LINKED ISSUE #446: Adding Financial Report for previous year defaults the year to 2020
Screen Shot 2020-11-13 at 3 24 24 PM

Screen Shot 2020-11-13 at 3 24 34 PM

Tested on Safari 14.0 on MacOS

### PR DESCRIPTION
**Pull request by harshvitra**
Fixes #446 

Also added function to render server sided errors

### CODE REVIEW

**Comment by sagararyal** [comment]
image

Can you ensure that existing reports don't disappear when submitting one report.

**Comment by norbertschuler** [comment]
I tried to test this PR, but got an error:

```
Unhandled Runtime Error
TypeError: Cannot read property 'getFullYear' of undefined

Source
src/features/user/ManageProjects/components/ProjectSpending.tsx (79:23) @ onSubmit

  77 | 
  78 |         const submitData = {
> 79 |             year: year.getFullYear(),
     |                       ^
  80 |             amount: updatedAmount,
  81 |             pdfFile: pdf
  82 |         }
Call Stack
FileReader.reader.onload
src/features/user/ManageProjects/components/ProjectSpending.tsx (56:16)
```

**Comment by norbertschuler** [comment]
- [ ] API rejects `amount: "2000,50"` which I was able to enter in the frontend (`2000,50` is the German writing for `2000.50`):

Bildschirmfoto 2020-12-09 um 10 48 49

**Comment by harshvitra** [comment]
we can take some knowledge from here. 
https://currency.js.org/

**Comment by norbertschuler** [comment]
> we can take some knowledge from here.
> https://currency.js.org/

We can either choose some existing modules for a numberParser with locale support, e.g. https://github.com/BrightspaceUI/intl or https://github.com/globalizejs/globalize#number-module or (if we do not want to add to much big npm module into our codebase) try to use our own small helper method as e.g. found here: https://stackoverflow.com/questions/55364947/is-there-any-javascript-standard-api-to-parse-to-number-according-to-locale as following:
```javascript
class NumberParser {
  constructor(locale) {
    const format = new Intl.NumberFormat(locale);
    const parts = format.formatToParts(12345.6);
    const numerals = Array.from({ length: 10 }).map((_, i) => format.format(i));
    const index = new Map(numerals.map((d, i) => [d, i]));
    this._group = new RegExp(`[${parts.find(d => d.type === "group").value}]`, "g");
    this._decimal = new RegExp(`[${parts.find(d => d.type === "decimal").value}]`);
    this._numeral = new RegExp(`[${numerals.join("")}]`, "g");
    this._index = d => index.get(d);
  }
  parse(string) {
    return (string = string.trim()
      .replace(this._group, "")
      .replace(this._decimal, ".")
      .replace(this._numeral, this._index)) ? +string : NaN;
  }
}

const formatter = new Intl.NumberFormat('ar-EG');
const parser = new NumberParser('ar-EG');
console.log(formatter.format(1234.5));               // ١٬٢٣٤٫٥
console.log(parser.parse(formatter.format(1234.5))); // 1234.5
```

**Comment by norbertschuler** [comment]
I would say, we should just fix the bug with the year in this PR and do not care about number parsing (do that in a different issue). @harshvitra maybe you can find out what's causing https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/616#issuecomment-741658684 and then finalize this PR?

**Comment by norbertschuler** [comment]
Rebased on develop branch.

**Comment by harshvitra** [comment]
> I would say, we should just fix the bug with the year in this PR and do not care about number parsing (I copied my comments in a different issue #679). @harshvitra maybe you can find out what's causing [#616 (comment)](https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/616#issuecomment-741658684) and then finalize this PR?

I have fixed the issue

**Pull request merged**
