### PR TITLE
Add support and share button

### LINKED ISSUE #291: User Profile (Public/Private)
- [x]  1. If the user is logged in show settings on their user page : eg: /t/username

- [x] 2. [Public View] If the target is present, show the target, otherwise, planted trees will be centered. 
- [x] 2. / 3. [Logged In] Show target as 0, and allow user to set target.
- [x] 2. / 3. [Logged In] If target not 0 allow user to edit target.

- [x] Truncate the user description at 420 - 450 words after punctuation. [similar concept is implemented on read More on Single Projects] Additional text appears in a popup component.

- [x] Align the Name of the User to Center when it takes more than 1 line.

- [x] 4. [Logged In] Show three buttons, please use font awesome svg icons.

- [x] 4. [Public View]  Use Support & Share buttons [Support button should not exist for TPOs]

- [ ] [Logged In]  Contributions section - Clicking on contribution - fly to the project on right, Hover contribution on left - popup project on right

Screen Shot 2020-10-05 at 3 20 12 PM

Screen Shot 2020-10-05 at 3 08 13 PM

Screenshot 2020-10-05 at 7 26 09 PM

### PR DESCRIPTION
**Pull request by captainamiedi**
Fixes #291 

Changes in this pull request:
- User should see support and share button
-
-

@sagararyal @harshvitra 
support

### CODE REVIEW

**Review by sagararyal — CHANGES_REQUESTED** [review]
- [x] Support button should not be shown for Tree Planting Organizations

- [ ] Correct the button size and font size according to design

- [ ] Both buttons do not work as of now.

**Comment by captainamiedi** [comment]
@sagararyal from the Issue, the functionality of the buttons are not stated.

**Comment by sagararyal** [comment]
- [ ] Share text is still `Lorem ipsum`

**Comment by harshvitra** [comment]
Sharing my own User profile show Copied to clipboard. 

Sharing someone else's user profile shows this. 

Screenshot 2020-11-19 at 11 20 21 AM

**Comment by norbertschuler** [comment]
Looks ok on a public profile:

Bildschirmfoto 2020-11-25 um 12 25 25

But looking wrong on own profile:

Bildschirmfoto 2020-11-25 um 12 25 59

**Comment by captainamiedi** [comment]
> Looks ok on a public profile:
> 
> Bildschirmfoto 2020-11-25 um 12 25 25
> 
> But looking wrong on own profile:
> 
> Bildschirmfoto 2020-11-25 um 12 25 59

On my device this is what i got. can you help me on steps to produce these error? Thanks
social22

**Comment by norbertschuler** [comment]
> On my device this is what i got. can you help me on steps to produce these error? Thanks

Test with German language.

**Comment by norbertschuler** [comment]
Share buttons look good now also with longer German translation resources:

Bildschirmfoto 2020-11-26 um 11 36 23

**Pull request merged**
