### PR TITLE
hide menu bar when searching

### LINKED ISSUE #148: On mobile menu bar should go behind the keyboard.
Screenshot_20200904-185019

on mobile when searching here, the menu bar shouldn't move up with the keyboard

### PR DESCRIPTION
**Pull request by sarveshpro**
Fixes #148 

Changes in this pull request:
- hide menu bar when searching

### CODE REVIEW

**Comment by sagararyal** [comment]
Do not merge.

**Review by Plant-for-the-Planet — CHANGES_REQUESTED** [review]
.

**Comment by sagararyal** [comment]
After search for no projects; Tabs are still shown. 

File

**Comment by harshvitra** [comment]
Will be started again from Develop

**Pull request closed without merging**
