### PR TITLE
Add contact details in Redeem

### LINKED ISSUE #607: TypeError: Cannot read property 'firstName' of undefined
Sentry Issue: [APP-20-NEXT-C9](https://sentry.io/organizations/plant-for-the-planet/issues/2075271692/?referrer=github_integration)

```
TypeError: Cannot read property 'firstName' of undefined
  at c (./src/features/donations/components/ShareOptions.jsx:23:41)
  at None (/_next/static/chunks/pages/t/%5Bid%5D-a8ebdfda6df7b8077f9d.js:1:47729)
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by harshvitra**
Fixes #607 

- [x] Sending contact details from the Redemption feature inside user profile. 

- [x] Checking if contact details exist or not and accordingly showing labels

### CODE REVIEW

**Comment by norbertschuler** [comment]
@harshvitra I also fixed this in https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/621 - your fix is nicer as you rewrote the file to TypeScript, but I added the use case where no user name if available at all in the Sharing Options. Are you sure we always have a username for the Sharing (from redeem, donation or legacy donation).

**Comment by harshvitra** [comment]
> @harshvitra I also fixed this in #621 - your fix is nicer as you rewrote the file to TypeScript, but I added the use case where no user name if available at all in the Sharing Options. Are you sure we always have a username for the Sharing (from redeem, donation or legacy donation).

We both should combine our solutions. I am not getting access to the donation test tool to check the claim feature. 
But I'm certain that the donations from the App are not working (they can with a little modification from the backend).

**Comment by norbertschuler** [comment]
> We both should combine our solutions. I am not getting access to the donation test tool to check the claim feature.
> But I'm certain that the donations from the App are not working (they can with a little modification from the backend).

Ok, I integrated my code into this PR and close my own PR.

**Comment by harshvitra** [comment]
Both the app donations and redeem donations do not have user details. So we can't implement. Lets merge this

**Review by norbertschuler — APPROVED** [review]

**Pull request merged**
