### PR TITLE
load total number of donated trees dynamically

### PR DESCRIPTION
**Pull request by norbertschuler**
Fixes https://planetfoundation.slack.com/archives/C015AEAU75Z/p1714117221663939?thread_ts=1713974028.645419&cid=C015AEAU75Z

Changes in this pull request:
- load the number of total donated trees dynamically

To-Do:
- [x] do we want to configure the URL for `https://automate.plant-for-the-planet.org/webhook/` in the environment like we already did for the Salesforce deplyoment defined as `WEBHOOK_URL`?
- do we really want to display this number dynamically?

### CODE REVIEW

**Review by mohitb35 — APPROVED** [review]
Codewise, LGTM.

I think the webhook url should be kept in the environment, we plan to do this while migrating the salesforce tenant to the multitenant project anyway.

Not sure if we want to hold off on release due to reasons of data consistency.

**Comment by norbertschuler** [comment]
Ok, I'll just keep this as a draft until releases will work normally again.

**Comment by sagararyal** [comment]
@mohitb35 What's the data inconsistency issue?

The numbers shared generally was from Q1. vs the query returns number for 1 week ago.

**Comment by mohitb35** [comment]
There isn't any issue as such, but we do choose to hardcode certain figures at times, and I wondered if this was one of those cases.

**Comment by mohitb35** [comment]
@norbertschuler We can release this now, since www1.plant-for-the-planet.org is now redirected to web.plant-for-the-planet.org, so changes will be visible.

**Comment by norbertschuler** [comment]
> @norbertschuler We can release this now, since www1.plant-for-the-planet.org is now redirected to web.plant-for-the-planet.org, so changes will be visible.

Ok, I added using an env named WEBHOOK_URL which I also added to all deployments at Heroku and Vercel.

**Pull request merged**
