### PR TITLE
Feature/support deep links

### PR DESCRIPTION
**Pull request by norbertschuler**
Fixes #479

Changes in this pull request:
- adding files for deep links of native apps
- added routes to support deep links for the native apps (not sure if they would also work without these routes)

Actually I think not all urls listed in the attached files are _real_ deep links as only a few open a special screen within the app.
The deep links doing more then opening the app mostly can be found at the following source code in the Treecounter-App: https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/d52ae1189c808481dd886fa5a45cfa0ac8a0551e/app/components/Menu/index.native.js#L94-L187

I tried to read them from the source code as following: `signup`, `account-activate`, `reset-password`, `competition`, `t`, `project` and `donate-trees`, e.g.:
- https://www.trilliontreecampaign.org/signup
- https://www.trilliontreecampaign.org/signup/vodafone
- https://www.trilliontreecampaign.org/account-activate/xxxxxxxxx
- https://www.trilliontreecampaign.org/reset-password/xxxxxxxxx
- https://www.trilliontreecampaign.org/competition/137
- https://www.trilliontreecampaign.org/t/norbert-schuler
- https://www.trilliontreecampaign.org/project/1
- https://www.trilliontreecampaign.org/t/donate-trees
- https://www.trilliontreecampaign.org/t/donate-trees/1

TODO: 
- [x] Abstract all the same pages for supporting a route to one single component as much as possible.
- [x] Test if deep links work with native apps

### CODE REVIEW

**Comment by norbertschuler** [comment]
For testing:
- https://www.trilliontreecampaign.org/competition/137
- https://planet-webapp-git-feature-supportdeeplinks.planetapp.vercel.app/competition/137

**Comment by norbertschuler** [comment]
For testing this PR e.g. with iOS you would temporarily have to add the Vercel URL of this build to the Treecounter App and deploy it on a test device where you can test the above links. Apply this diff:

```
diff --git a/ios/TreecounterApp/TreecounterApp.entitlements b/ios/TreecounterApp/TreecounterApp.entitlements
index 8a7d6807..042a472d 100644
--- a/ios/TreecounterApp/TreecounterApp.entitlements
+++ b/ios/TreecounterApp/TreecounterApp.entitlements
@@ -5,6 +5,7 @@
 	<key>com.apple.developer.associated-domains</key>
 	<array>
 		<string>applinks:www.trilliontreecampaign.org</string>
+		<string>applinks:planet-webapp-git-feature-supportdeeplinks.planetapp.vercel.app</string>
 	</array>
 </dict>
 </plist>
```
or manually add it with Xcode:
Bildschirmfoto 2020-11-29 um 11 04 07

**Review by harshvitra — COMMENTED** [review]
It just shows Opening app... with no action on the mobile.

I have the app installed

**Comment by norbertschuler** [comment]
> It just shows Opening app... with no action on the mobile.
> 
> I have the app installed

One thing I had experienced with deep links. Opening an URL directly in the browser does not open the app, but loads the website. The deep links open the app if you click on them in a browser or in an mail or anywhere else on your mobile device. I agree the message "Opening app..." is wrong if I we not put a link with the same URL the browser just got opened with underneath the text, so the user can click on it.

**Comment by norbertschuler** [comment]
@sagararyal do we want to remove some deep links from the iOS file here to solve #584 ?

**Pull request merged**
