### PR TITLE
Fix satellite map when switching between map modes

### PR DESCRIPTION
**Pull request by sarveshpro**
reset map zoom when changing modes

### CODE REVIEW

**Comment by sagararyal** [comment]
Some issues still remain.
Uploading Screen Recording 2021-08-19 at 10.07.23 PM.mov…

**Review by sagararyal — CHANGES_REQUESTED** [review]
check video.

**Comment by sarveshpro** [comment]
@sagararyal check zoom buttons now

**Comment by norbertschuler** [comment]
This is how zoom buttons look like on landscape mode on an iPhone X overlapping with another button, but it’s probably an edge case:
399CF2C9-9518-4B46-B362-0A937B4BA45B

**Comment by sarveshpro** [comment]
> This is how zoom buttons look like on landscape mode on an iPhone X overlapping with another button, but it’s probably an edge case:
> 

Not sure why the project details is taking full width in landscape mode.
It should be more like this. Although this is not specific to this PR. You can create a new issue for this.
image

**Comment by norbertschuler** [comment]
> Not sure why the project details is taking full width in landscape mode.

The iPhone X simulation in my Chrome browser behaves different from my real iPhone X. It's more like on an iPhone 5 simulation in Chrome where the projects are shown with full width.

> It should be more like this. Although this is not specific to this PR. You can create a new issue for this.

I create a new issue #1204.

**Pull request merged**
