### PR TITLE
Prevent multiple clicks

### PR DESCRIPTION
**Pull request by prachigarg19**
Create a context to prevent multiple clicks/ multiple api requests on a button.

### CODE REVIEW

**Comment by mariahosfeld** [comment]
@prachigarg19 , can you add the description to the PR?

**Review by norbertschuler — COMMENTED** [review]
Code seems valid to me. I currently have no redeem voucher for testing.

**Review by sunilsabatp — APPROVED** [review]

**Review by sunilsabatp — COMMENTED** [review]
resolve the merge conflicts and code factor  errors

**Comment by mariahosfeld** [comment]
Functionality seems fine, tested redeeming a code.

**Comment by mohitb35** [comment]
@prachigarg19 IMO, keeping the `disable` state in `UserPropsContext` isn't advisable because
1. `disable` does not have anything to do with a `User` - it indicates the state of a `button`
2. Keeping this in context can lead to conflicts when multiple components try to access or update `disable`. It seems to me like local state (or button component state - but that would need a change in structure in multiple places) would be a more suitable place to store this value.

**Comment by mohitb35** [comment]
Closed as we've decided not to take this approach.

Ref - https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1707#issuecomment-1539370905

**Pull request closed without merging**
