### PR TITLE
Feature/treemapper

### PR DESCRIPTION
**Pull request by sarveshpro**
To do - 

- [x] multiple tree  polygons
- [x] mobile view
- [x] expand row zooms to location

### CODE REVIEW

**Comment by norbertschuler** [comment]
- [ ] the header is covering parts of the layouts for adding new projects or registering trees (testing on latest MacOS with latest Chrome):

Bildschirmfoto 2021-05-20 um 10 08 20
Bildschirmfoto 2021-05-20 um 10 09 02

**Comment by norbertschuler** [comment]
Adding some screenshot of how it's currently looking for me on development backend:
- Should we show all polygons on the map in the detail view or just the one chosen to view?
- Some of my registrations are showing broken images (as the images are missing, but that might be just corrupted data from early tests)
- The fields needs translations and formatting of the data, but of course it works in progress ;-)

Bildschirmfoto 2021-05-20 um 10 13 56
Bildschirmfoto 2021-05-20 um 10 13 30
Bildschirmfoto 2021-05-20 um 10 18 55

**Comment by norbertschuler** [comment]
- [ ] It makes no more sense to hide the menu item to show the account history in the settings menu as it is now accessible through the account header navigation menu as well.

**Comment by norbertschuler** [comment]
- [ ] An error happens when a user is doing a logout:

Bildschirmfoto 2021-05-20 um 10 41 44

**Comment by norbertschuler** [comment]
- [ ] Account history is currently showing NaN for the donation amount (@jmiridis `paidAmount` is null in the API response of GET https://app-development.plant-for-the-planet.org/app/paymentHistory)

Bildschirmfoto 2021-05-20 um 10 52 25

**Comment by norbertschuler** [comment]
- [ ] In the filter options the filter text is sometimes breaking the layout (button width should be dynamic) - this error is in both version of the filter (for small and bigger screens):

Bildschirmfoto 2021-05-24 um 12 02 55
Bildschirmfoto 2021-05-24 um 12 08 57

**Comment by norbertschuler** [comment]
> * [ ]  An error happens when a user is doing a logout:

This error is still happening to me when I logout of an TPO account.

**Comment by norbertschuler** [comment]
> * [x]  Account history is currently showing NaN for the donation amount (@jmiridis `paidAmount` is null in the API response of GET https://app-development.plant-for-the-planet.org/app/paymentHistory)

- [ ] I now get the `NaN` at another place:

Bildschirmfoto 2021-05-24 um 12 16 23

- [ ] Also in the details view (which btw. does not show any header):

Bildschirmfoto 2021-05-24 um 12 14 20

**Comment by norbertschuler** [comment]
> > * [ ]   An error happens when a user is doing a logout:
> 
> * [ ]  This error is still happening to me when I logout of an TPO account if you logout e.g. from the URL http://localhost:3000/account/history - not sure what's different from logging out from the personal page at e.g. http://localhost:3000/t/norbert - please test all the different pages from which you can logout now!

- [ ] If you logout from http://localhost:3000/account/register-trees the user stays on the same URL showing a blank page instead getting redirecting to the home screen after being logged out:

Bildschirmfoto 2021-05-24 um 12 28 41

**Comment by sarveshpro** [comment]
working on these

**Comment by norbertschuler** [comment]
> > * [x]   An error happens when a user is doing a logout:
> 
> * [x]  This error is still happening to me when I logout of an TPO account if you logout e.g. from the URL http://localhost:3000/account/history - not sure what's different from logging out from the personal page at e.g. http://localhost:3000/t/norbert - please test all the different pages from which you can logout now!

- [ ] The error got fixed in `newAccountHeader.tsx`, but not in `accountHeader.tsx` which still seems to be used. I fixed it and I would like to know if both headers should exists in parallel or if this is a transition process from one file to another which will be finished before we merge this?

Bildschirmfoto 2021-05-25 um 09 23 15

**Comment by norbertschuler** [comment]
- [ ] Can we show the empty folder icons as in the account history if nothing exists to show in the Treemapper tab?

Bildschirmfoto 2021-05-25 um 09 38 04

**Comment by norbertschuler** [comment]
- [ ] Sometimes I get crashes on logout like this - maybe there are some race conditions where the userprofile context is already deleted, but some code still tries to access it?

Bildschirmfoto 2021-05-25 um 09 45 08

**Comment by norbertschuler** [comment]
- [ ] I think the back button in the header should not go back using the browser history (as otherwise e.g. jumping back through all the menus selected), but rather directly go back to the user profile:

https://user-images.githubusercontent.com/1532418/119462234-cb390380-bd40-11eb-84d6-8ef58662560c.mp4

**Comment by sarveshpro** [comment]
fixed back button to go to user profile

**Comment by sarveshpro** [comment]
> * [ ]  It makes no more sense to hide the menu item to show the account history in the settings menu as it is now accessible through the account header navigation menu as well.

@sagararyal Can these features go in develop in the current state and improved in new PRs? then I'll add back `/account` in the settings modal which will take the user to `/account/history`

**Comment by sarveshpro** [comment]
> > > * [x]    An error happens when a user is doing a logout:
> > 
> > 
> > 
> > * [x]   This error is still happening to me when I logout of an TPO account if you logout e.g. from the URL http://localhost:3000/account/history - not sure what's different from logging out from the personal page at e.g. http://localhost:3000/t/norbert - please test all the different pages from which you can logout now!
> 
> * The error got fixed in `newAccountHeader.tsx`, but not in `accountHeader.tsx` which still seems to be used. I fixed it and I would like to know if both headers should exists in parallel or if this is a transition process from one file to another which will be finished before we merge this?
> 
> Bildschirmfoto 2021-05-25 um 09 23 15

It was a transition, got rid of the old code. It was also resulting in builds failing

**Pull request merged**
