### PR TITLE
TreeMapper Feature Release

### PR DESCRIPTION
**Pull request by sarveshpro**
- [ ] depends on backend release!

To test

- [x] Donations
- [x] Project Pages
- [x] Maps Functionality
- [x] Login
- [x] Profile Pages
- [x] Register Trees
- [x] Manage Projects
- [x] Gifts

Deployments to test -
https://ttc-staging.netlify.app/ - TTC tenant, production, Netlify
https://dev.pp.eco/ - Planet tenant, staging, Vercel (for testing donations, gifts)
https://planet-app-dev.herokuapp.com/ - Planet tenant, production, Heroku

To test plant locations (TreeMapper) check Yucatan Project on production

UI issues found:

- [x] White polygons rarely visible on map with a lot of streets on it https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1157#issuecomment-887851014
- [x] Text labels missing on iOS and Safari on MacOS https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1157#issuecomment-887852041
- [x] Tree mappings rarely visible on satellite view with green areas https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1157#issuecomment-888457842
- [x] Not possible to switch to satellite view on mobile devices https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1157#issuecomment-888619538

### CODE REVIEW

**Review by norbertschuler — APPROVED** [review]
I did just a very short test of the website, but everything I tested seems to work.

**Comment by norbertschuler** [comment]
- [ ] Try to spot the polygons on https://planet-app-dev.herokuapp.com/reunion-anillo-verde-de-granada-phase-i - it’s hard to see them in the default map mode (no satellite view) 🙂 Maybe we need to paint them in another color as white?

**Comment by norbertschuler** [comment]
- [ ] On my iPhone or on Safari on MacOS I don’t see „13d ago“ labels at https://planet-app-dev.herokuapp.com/yucatan

**Comment by norbertschuler** [comment]
- [ ] tree mappings are not well visible in satellite mode and should be limited to the normal map:

Bildschirmfoto 2021-07-28 um 18 39 24

**Comment by norbertschuler** [comment]
- [ ] It does not seem possible to switch to satellite view on mobile devices as you can not access the icon to switch. 

7924CEA7-18E0-4B71-851C-B0C8B9B53695

**Comment by sagararyal** [comment]
#### 📝Changed routes:


| [**/\[p\]**](https://planet-webapp-nel3pcaxx-planetapp.vercel.app/[p]) | [**/\[p\]/\[id\]**](https://planet-webapp-nel3pcaxx-planetapp.vercel.app/[p]/[id]) |
|:-:|:-:|
|<a href="https://planet-webapp-nel3pcaxx-planetapp.vercel.app/[p]">Screenshot of /[p]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/jEedrZz5lZAmLiV8qjh-BRy3rowONDXvT45VrGHN-VOColDEUJfE7bb2TBtrlub33w1E97tpSg8R59kokd985w.png">(view full size)</a> |<a href="https://planet-webapp-nel3pcaxx-planetapp.vercel.app/[p]/[id]">Screenshot of /[p]/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xatUDTF8xbLYefU298QldAJNeXkvVHcppQiQWTNKQctIscLHmhquSJxenWJJWOI1qg-Fovw5AW-tRYViedFZUw.png">(view full size)</a> |



| [**/**](https://planet-webapp-nel3pcaxx-planetapp.vercel.app/) |
|:-:|
|<a href="https://planet-webapp-nel3pcaxx-planetapp.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/jxEgEeO8BWZshd_YPgw6lG9VIruvveaIoi6iaBiYAtanbe0vz6EGVsuiYDu0cwDVIBgqGkl9SlkUN52vdrOOpQ.png">(view full size)</a> |







Commit 1af57c13997db5097a234450801d762ac0aa4c98 (https://planet-webapp-nel3pcaxx-planetapp.vercel.app).

**Comment by norbertschuler** [comment]
- [ ] No satellite data shown if switching between field-data and time-travel and back on the use case with very high zoom level e.g. https://planet-webapp-ccion87lw-planetapp.vercel.app/plant-for-ethiopia.

**Review by norbertschuler — APPROVED** [review]
I updated the deployments to Netlify and Heroku and checks some basic stuff (view projects, login, donating, registering trees as TPO with project). It still seems to work.

**Pull request merged**
