### PR TITLE
Recurrent donation history

### PR DESCRIPTION
**Pull request by tejassonar**
Changes in this pull request:
- Recurrent Donation History and manage Donations

To-Do:
- [x] merge develop and solve merge conflicts
- [x] fix i18n issue https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1290#issuecomment-970471760
- [ ] fix dark mode issues https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1290#issuecomment-971318224 (optional)

### CODE REVIEW

**Comment by sagararyal** [comment]
#### 📝 Changed routes:


| [**/profile/recurrency**](https://planet-webapp-5u8lul4xb-planetapp.vercel.app/profile/recurrency) |
|:-:|
|<a href="https://planet-webapp-5u8lul4xb-planetapp.vercel.app/profile/recurrency">Screenshot of /profile/recurrency</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/wgwLr7HYKZESp6E_QsAwIWibfmszwL5yzQUHOCgtam2E4AXLCRepNbPw9QxW1fAr1OHQoqrW-TzLgyUxmtwsPQ.png">(view full size)</a> |







Commit 772aad0ba0fecb4476030ad02af8f6c9338bfcf3 (https://planet-webapp-5u8lul4xb-planetapp.vercel.app).

**Comment by norbertschuler** [comment]
> * [x]  When using the small screen layout to look at a single recurrent donation and clicking the headline to collapse the entry, an error got raised as this view does not show a list of recurrent donations, but only a single one with an back arrow:
> 
> ```
> Uncaught TypeError: i is not a function
>     at onClick (RecurrencyRecord.tsx:91)
> ```

- [ ] I noticed the same error happens when clicking on the header of an item in the history of donations in the small screen design - maybe the same fix can be applied here?

Bildschirmfoto 2021-11-13 um 18 02 02

**Comment by norbertschuler** [comment]
- [ ] The date until as recurrent donation is paused (if a date is chosen at pausing) is not shown in the UI - we should somehow communicate it:

Bildschirmfoto 2021-11-13 um 18 09 16

**Comment by norbertschuler** [comment]
- [ ] If a recurrent donation is cancelled to a certain date, the editing dialog shows a error for the date of the recurrency - maybe we should think about if a recurrent donation with a cancellation in progress should not be able to be edited any more?

Bildschirmfoto 2021-11-13 um 18 14 21

**Review by norbertschuler — DISMISSED** [review]
Check my above comments.

**Comment by norbertschuler** [comment]
- [ ] Not sure if options "monthly" and "yearly" can be translated as I do not find them as resources, but just twice as strings in the source code in `Recurrency.tsx` and `EditModal.tsx`:

Bildschirmfoto 2021-11-16 um 17 57 02

**Comment by norbertschuler** [comment]
- [ ] Does not yet support dark mode very well:

Bildschirmfoto 2021-11-17 um 08 39 37
Bildschirmfoto 2021-11-17 um 08 41 52
Bildschirmfoto 2021-11-17 um 08 43 35

**Review by norbertschuler — APPROVED** [review]
LGFM (except for the dark mode).

**Pull request merged**
