### PR TITLE
migrate webpack from 4 to 5

### PR DESCRIPTION
**Pull request by norbertschuler**
@sarveshpro I tried to fix the build of https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1022, but only succeeded with using webpack5 with all the necessary upgrades.

Changes in this pull request:
- migrated to webpack 5 according to https://nextjs.org/docs/messages/webpack5
- fixed failed BrowserStack test

To-Do:

- [x] test local deployment with `npm run dev` or `npm run build` and `npm run start -p 3000`
- [x] test Vercel deployment
- [x] test Cloudflare deployment
- [x] test Netlify deployment
- [x] test Heroku deployment

### CODE REVIEW

**Review by sarveshpro — APPROVED** [review]
LGTM ✔

**Comment by sarveshpro** [comment]
This issue is now in develop. need to get this fix merged ASAP.

**Review by sarveshpro — APPROVED** [review]
Tested this on - 
locally - `build` `start` and run `dev` both
Netlify - https://planet-sarvesh.netlify.app/
heroku - https://planet-app-dev.herokuapp.com/
vercel - https://planet-webapp-git-feature-webpack5-planetapp.vercel.app/
cloudflare - https://5e33facd.planet-2dm0.pages.dev/

projects, maps, donations, login worked on all. except for Cloudflare where donation and login failed, but I think it was because of misconfiguration.

**Comment by norbertschuler** [comment]
> Tested this on -
> 
> projects, maps, donations, login worked on all. except for Cloudflare where donation and login failed, but I think it was because of misconfiguration.

Thank you for testing. Auth0 config probably only allows localhost and vercel URLs, so it cannot be tested on Heroku, Cloudflare or Netlify.

**Comment by sarveshpro** [comment]
I think this is good to merge now. all tests are passing 🎉

**Pull request merged**
