### PR TITLE
set map style to satellite if no treemapper data found

### PR DESCRIPTION
**Pull request by sarveshpro**

### CODE REVIEW

**Review by norbertschuler — COMMENTED** [review]
Difficult to test without data on staging, so I tested with production API :-)
Looks o.k. for me, but this feature might be irritating for the users if no tree mapping data exists for the first area shown but only for other areas of the project not visible at first sight.

**Comment by sarveshpro** [comment]
addition to this also added a fallback to default style if user zooms to zoom level more than 15 while on satellite view.
avoiding this
image

**Comment by sarveshpro** [comment]
fixes #1163

**Comment by norbertschuler** [comment]
> fixes #1163

You removed this again, right? So I unlinked the issue again too.

**Review by norbertschuler — APPROVED** [review]
Works for me. Not fixing "fallback to default style if user zooms to zoom level more than 15 while on satellite view".

**Review by norbertschuler — APPROVED** [review]

**Comment by sarveshpro** [comment]
Yes, we decided to not fix that because in some areas we do have more detailed imagery, and we don't want it to be missed out. There's a fix for this we will define max zoom level for each project on the backend.

**Pull request merged**
