### PR TITLE
navbar moved to top on mobile screens

### PR DESCRIPTION
**Pull request by sarveshpro**
### Changes to test -
- in mobile view, navbar should be on top
- check if everything else is visible properly

### CODE REVIEW

**Comment by delightedMatt** [comment]
Checked https://planet-webapp-git-feature-move-mobile-navigati-379af8-planetapp.vercel.app/
on multiple mobile screens (android and ios) and it was fully displayed on all.

But the menu beneath "About Us" does not get opened in portrait mode.
Or at least it doesn't open into the visible screen area (Maria saw it opening up out of her screen on her phone).
==> Still needs to get fixed @sarveshpro 

The About Us menu does however get opened in landscape mode.

**Review by norbertschuler — DISMISSED** [review]
Nice, but I agree with Matthias the about us drop down menu does not work in portrait mode, but only in landscape mode.

Unfortunately this change still does not solve the [problem](https://github.com/Plant-for-the-Planet-org/planet-webapp/issues/1166), the imprint and the other links from the bottom menu are still not accessible on mobile devices.

**Review by tejassonar — APPROVED** [review]

**Review by delightedMatt — APPROVED** [review]
Reviewed functionality for different iOS and Android devices.
Everything worked.

**Comment by mariahosfeld** [comment]
I checked the latest deployment with iOS settings on portrait and when selecting "Leaders" the navbar overlaps the headline of the page:
grafik

**Review by norbertschuler — DISMISSED** [review]
I agree to @mariahosfeld - leaderboard page ('/all') is not showing the title correctly.

**Review by norbertschuler — DISMISSED** [review]
Top navigation elements on home screen and details screen of a projects are still covered and not accessible any more:

now:
Bildschirmfoto 2022-03-07 um 08 24 31
Bildschirmfoto 2022-03-07 um 08 25 07


before:
Bildschirmfoto 2022-03-07 um 08 27 31
Bildschirmfoto 2022-03-07 um 08 26 11

**Comment by sarveshpro** [comment]
> Top navigation elements on home screen and details screen of a projects are still covered and not accessible any more:
> 

Fixed

**Pull request merged**
