### PR TITLE
Added landing video

### PR DESCRIPTION
**Pull request by harshvitra**
Added landing video 

When you skip it will not show again unless local storage is cleared

- [x] after video is complete load the app
- [x] 2 different videos for mobile and desktop

To-Do:

- [x] Support more languages - at least `de`, `en`, `es` which are already programmed? (for now, we continue with current languages)
- [ ] Support our Browserstack test to work with the intro? https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/820#issuecomment-787918909
- [x] Does the video download twice? Should it be hosted elsewhere? https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/820#issuecomment-822795040

### CODE REVIEW

**Comment by norbertschuler** [comment]
- [ ] Tested on latest MacOS with latest Chrome on a high resolution screen the video was zoomed in too far to see all of it's content area:

Bildschirmfoto 2021-02-15 um 18 58 23

**Comment by norbertschuler** [comment]
- [ ] Check lint error:

```
/home/runner/work/planet-webapp/planet-webapp/src/features/common/LandingVideo/index.tsx
  26:78  error  Unknown property 'allowfullscreen' found, use 'allowFullScreen' instead  react/no-unknown-property
```

**Comment by harshvitra** [comment]
> * [ ]  Check lint error:
> 
> ```
> /home/runner/work/planet-webapp/planet-webapp/src/features/common/LandingVideo/index.tsx
>   26:78  error  Unknown property 'allowfullscreen' found, use 'allowFullScreen' instead  react/no-unknown-property
> ```

Sorry for the incorrect commit name, but pushed this

**Comment by harshvitra** [comment]
> * [ ]  Tested on latest MacOS with latest Chrome on a high resolution screen the video was zoomed in too far to see all of it's content area - I assume it just does not fit into the screen if the aspect-ratio does not match (hint: try a mobile device):

Either we need different videos or we need video that has all main content in center designed to fit all screens

**Comment by norbertschuler** [comment]
> Either we need different videos or we need video that has all main content in center designed to fit all screens

I do not think we can adapt the video to fit on a mobile device in portrait mode - we maybe have to think of another solution for that use case?

Bildschirmfoto 2021-02-17 um 10 56 12

**Review by norbertschuler — CHANGES_REQUESTED** [review]
Almost got crazy testing why language and screen size did not work until I recognized the four videos with the four different names are currently all the same video - this should not be merged before the distinct videos got produced :-)

**Comment by norbertschuler** [comment]
- [ ] Browserstack payments test needs to get adapted as they can not deal with the video yet: 

```
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".theme-light"}
      4 | const rootSelector = { css: '.theme-light' };
      5 | 
    > 6 | export const root = () => driver.findElement(rootSelector);
```

**Comment by sagararyal** [comment]
- [ ] Remove button motion, it is too erratic. 

Screen Shot 2021-04-19 at 2 16 03 PM

**Comment by sagararyal** [comment]
Seems, both web and mobile version are being downloaded.
Screen Shot 2021-04-19 at 11 23 01 PM

**Comment by norbertschuler** [comment]
It does not make sense to keep the Priority label here and not working on it anymore.

**Pull request merged**
