### PR TITLE
add polygon icon to sites dropdown

### LINKED ISSUE #1130: Polygon Icon in Desktop Version
Please display the polygon icon we use in the mobile version of the site, just left of the site name in the web version

Screenshot 2021-06-20 at 10 44 01

### PR DESCRIPTION
**Pull request by sarveshpro**
Fixes #1130 #1146

### CODE REVIEW

**Comment by norbertschuler** [comment]
- [ ] It's overlapping with the icons on the left side now, so you can not click them (iPhoneX):

Bildschirmfoto 2021-06-23 um 11 57 05

**Comment by sarveshpro** [comment]
https://planet-webapp-git-feature-sites-icon-planetapp.vercel.app/community-based-restoration-at-el-silencio-natural-reserve

**Comment by norbertschuler** [comment]
- [ ] Still looking like this for me at https://planet-webapp-11xgja4zq-planetapp.vercel.app/20-million-trees-for-kenya-s-forests

Bildschirmfoto 2021-07-19 um 12 13 54

**Comment by sarveshpro** [comment]
check now

> * [x]  Still looking like this for me at https://planet-webapp-11xgja4zq-planetapp.vercel.app/20-million-trees-for-kenya-s-forests
> 
> Bildschirmfoto 2021-07-19 um 12 13 54

check now

**Comment by norbertschuler** [comment]
> check now

- [ ] Dropdown closes if you change the area, but stays open if you selected the same item again.

**Comment by sarveshpro** [comment]
closes if clicked anywhere else on the map

**Review by norbertschuler — APPROVED** [review]

**Comment by norbertschuler** [comment]
@sarveshpro please clarify if #1146 also gets fixed by this. Then I think we can merge it.

**Comment by sarveshpro** [comment]
Yes it does

**Pull request merged**
