### PR TITLE
Code-cleanup/data-explorer

### PR DESCRIPTION
**Pull request by Shreyaschorge**
- Code cleanup for data explorer feature
- Add counter feature

### CODE REVIEW

**Comment by norbertschuler** [comment]
- [ ] I am not sure if it is related to this PR, but I get this dialog missing the country names when switching the language from the data explorer screen: 

Bildschirm­foto 2023-04-01 um 11 01 27

**Comment by Shreyaschorge** [comment]
> * [ ]  I am not sure if it is related to this PR, but I get this dialog missing the country names when switching the language from the data explorer screen:
> 
> Bildschirm­foto 2023-04-01 um 11 01 27

Fixed here https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1720/commits/ee492f1f86b6387b1550c3a438abc7a759343cf7

**Comment by mariahosfeld** [comment]
> > * [ ]   I am not sure if it is related to this PR, but I get this dialog missing the country names when switching the language from the data explorer screen:
> > 
> > Bildschirm­foto 2023-04-01 um 11 01 27
> 
> Fixed here [ee492f1](https://github.com/Plant-for-the-Planet-org/planet-webapp/commit/ee492f1f86b6387b1550c3a438abc7a759343cf7)

Can confirm, I see the correct dialog in the PR.

**Comment by mariahosfeld** [comment]
Layout wise it might be good to add boundaries around the counter, the it will not look like it is "hanging" there. Otherwise functionality is working.

**Comment by mariahosfeld** [comment]
Shadows look much better now.

**Review by sunilsabatp — APPROVED** [review]

**Pull request merged**
