### PR TITLE
scroll for iphone

### LINKED ISSUE #543: Several buttons not clickable on iPhone
**Describe the bug**
The dialogs for signing up, editing profile or registration of trees cannot be scrolled down far enough to submit them with the button  at the bottom. 

**Is it on a Production or Development Build?**
production 

**Screenshots**
100932207-cdd24300-34eb-11eb-919f-7fa71e6c2190100932212-cf9c0680-34eb-11eb-8411-107514c5171b100932218-d165ca00-34eb-11eb-83d5-9dd61f927833

**Smartphone (please complete the following information):**
- Device: iPhone X
- OS: latest iOS 
- Browser: Chrome

### PR DESCRIPTION
**Pull request by captainamiedi**
Fixes #543 

Changes in this pull request:
-
-
-
- [x] signup
@sagararyal

### CODE REVIEW

**Comment by norbertschuler** [comment]
Still not working for me - @captainamiedi have you tested with an iPhone (Browserstack or Simulator or real device)?

See this video (hopefully I had no old data in my cache):
[RPReplay_Final1607103640.MP4.zip](https://github.com/Plant-for-the-Planet-org/planet-webapp/files/5644394/RPReplay_Final1607103640.MP4.zip)

**Comment by captainamiedi** [comment]
> Still not working for me - @captainamiedi have you tested with an iPhone (Browserstack or Simulator or real device)?
> 
> See this video (hopefully I had no old data in my cache):
> [RPReplay_Final1607103640.MP4.zip](https://github.com/Plant-for-the-Planet-org/planet-webapp/files/5644394/RPReplay_Final1607103640.MP4.zip)

Kindly test the edit profile and register trees. I have not been able to sign up. The link i got to verify email isn't working

**Comment by norbertschuler** [comment]
I can access the button for signup, but the layout is not very pretty any more now:

IMG_89ED8F0932AE-1

**Comment by captainamiedi** [comment]
@norbertschuler kindly check again. Thanks

**Comment by norbertschuler** [comment]
> @norbertschuler kindly check again. Thanks

Still some weird behavior if trying to scroll down twice, but at least I can access the button now:

[RPReplay_Final1607109472.MP4.zip](https://github.com/Plant-for-the-Planet-org/planet-webapp/files/5644951/RPReplay_Final1607109472.MP4.zip)

**Comment by sagararyal** [comment]
you can increase the z-index to be highest so the card is at top of everything including bottom menu

**Review by norbertschuler — APPROVED** [review]
Working very well on my iPhone now.

**Review by norbertschuler — CHANGES_REQUESTED** [review]
I am afraid this makes the signup in my normal Chrome browser (Mac OS X) look bad by adding a white area at the bottom - so not yet merging it:
Bildschirmfoto 2020-12-05 um 10 50 15

**Review by norbertschuler — APPROVED** [review]
Working on iPhone and on MacBook now for me.

**Pull request merged**
