### PR TITLE
Release: User Impersonation

### PR DESCRIPTION
**Pull request by mohitb35**
**Contains:**

#1672 feature: page for switch user
#1699 fix scrollbar
#1702 Feature/cleanup user impersonation
#1708 Hide scrollbar

### CODE REVIEW

**Comment by sagararyal** [comment]
#### 📝 Changed routes:


| [**/404**](https://planet-webapp-la47ih73k-planetapp.vercel.app/404) | [**/claim/\[type\]/\[code\]**](https://planet-webapp-la47ih73k-planetapp.vercel.app/claim/[type]/[code]) |
|:-:|:-:|
|<a href="https://planet-webapp-la47ih73k-planetapp.vercel.app/404">Screenshot of /404</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/mj4WPgbcB0djSvpc_rXLEHUCBxXTQ9kLhUz0EEs4nIztivJPaFjZ2An_fnjJafTgqGWWP4MYDzgR31pP4CRzAQ.png">(view full size)</a> |<a href="https://planet-webapp-la47ih73k-planetapp.vercel.app/claim/[type]/[code]">Screenshot of /claim/[type]/[code]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ZrDNiyxSx1wd3s-0FpbYr1H1sJ5z-tgGE9-1pjtpt_c-fpIMSWkCHQ_8gezJNx71Rs3J2e3Jqt4ae8iuWufv3w.png">(view full size)</a> |



| [**/profile/history**](https://planet-webapp-la47ih73k-planetapp.vercel.app/profile/history) | [**/profile/impersonate-user**](https://planet-webapp-la47ih73k-planetapp.vercel.app/profile/impersonate-user) |
|:-:|:-:|
|<a href="https://planet-webapp-la47ih73k-planetapp.vercel.app/profile/history">Screenshot of /profile/history</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/kLeUFz41CWJPO751GTyVLji-qHUa2I_eN9dn3l6EFMA9ohUj9pWDoKCCinDoiih5MZaNOU7ZDeGrpj7oDPlzGg.png">(view full size)</a> |<a href="https://planet-webapp-la47ih73k-planetapp.vercel.app/profile/impersonate-user">Screenshot of /profile/impersonate-user</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/DhGVlptOynyBOqyaeWnX_osGnnBGlFbeYmaND-SWxyfKtgA2FQ1DK2iazfRXzgSmTfxvmZSGDNbnExwJFMF-oA.png">(view full size)</a> |



| [**/profile/projects/\[id\]**](https://planet-webapp-la47ih73k-planetapp.vercel.app/profile/projects/[id]) | [**/profile/recurrency**](https://planet-webapp-la47ih73k-planetapp.vercel.app/profile/recurrency) |
|:-:|:-:|
|<a href="https://planet-webapp-la47ih73k-planetapp.vercel.app/profile/projects/[id]">Screenshot of /profile/projects/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/JHh6AxJkVIgS0nHxoBePgZ-NuFpGicwQbqUN3o9J4eTgHbnz-kwLfNklIAX83T67w1pwBQIfFxpwnfw65MtfaQ.png">(view full size)</a> |<a href="https://planet-webapp-la47ih73k-planetapp.vercel.app/profile/recurrency">Screenshot of /profile/recurrency</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/EeerltYYwVco6hctP0Sz8JRM1vPkQnpXdGTqQH0qk4muLVoSpezQvO4qipvVu078cPjjglMDKmYC4sapN02L6A.png">(view full size)</a> |



And 1 other route:
- [**/profile/redeem/\[code\]**](https://planet-webapp-la47ih73k-planetapp.vercel.app/profile/redeem/[code])



Commit 62069f563210273ede2fdefd4866384334d588c6 (https://planet-webapp-la47ih73k-planetapp.vercel.app).

**Comment by mariahosfeld** [comment]
Impersonation feature is looking good.

**Comment by mariahosfeld** [comment]
Functionality looks good to me.

**Comment by prachigarg19** [comment]
When impersonation is on, the scrollbar is visible.

**Review by prachigarg19 — APPROVED** [review]

**Pull request merged**
