### PR TITLE
Projects redesign/minor UI fixes

### PR DESCRIPTION
**Pull request by mohitb35**
This pull request focuses on making minor UI fixes as part of the projects redesign.

### CODE REVIEW

**Review by mariahosfeld — CHANGES_REQUESTED** [review]
- [x] change also color of "x" button to link color
image
- [ ] on mobile also add an opaque circle behind "x" to exit Dive into Project, when using Satellite view, it gets kind of lost. (comparable to image slider expansion on mobile)

**Comment by mohitb35** [comment]
> * [x]  change also color of "x" button to link color
>   image
> * [x]  on mobile also add an opaque circle behind "x" to exit Dive into Project, when using Satellite view, it gets kind of lost. (comparable to image slider expansion on mobile)

@mariahosfeld Resolved, can be rechecked

**Review by mariahosfeld — APPROVED** [review]
Changes look good to me.

**Review by mariahosfeld — CHANGES_REQUESTED** [review]
Just noticed: in the project list itself, I just see the green loader, not the new one, as it is already visible for the pop-up.

**Comment by mohitb35** [comment]
> Just noticed: in the project list itself, I just see the green loader, not the new one, as it is already visible for the pop-up. At least for the top-projects this has to still be adapted.

There is no difference between the popup and the list. You may see a brief splash of the green background before the default image loads - leaving that background out resulted in a blank background getting replaced by the green default image, and that effect was more jarring than having a green background already in place.

**Review by mariahosfeld — APPROVED** [review]

**Comment by sunilsabatp** [comment]
Could we shift the cross icon a little to the left to align it with the other icon (i.e., the satellite icon)?
image

**Comment by mohitb35** [comment]
> Could we shift the cross icon a little to the left to align it with the other icon (i.e., the satellite icon)? image

Fixed

**Review by sunilsabatp — APPROVED** [review]

**Pull request merged**
