### PR TITLE
Refactors map for better performance while showing a single project

### PR DESCRIPTION
**Pull request by shyambhongle**
Fixes

Changes in this pull request:
Code refactor to improve map performance. 
Use of geoJSON filters instead of mapping.

@mohitb35

### CODE REVIEW

**Comment by norbertschuler** [comment]
Zooming is working better than in the current develope branch, but when I test this locally with `npm run dev` I sometimes experiences this crash:

Bildschirmfoto 2024-05-27 um 14 34 34

**Comment by norbertschuler** [comment]
> > Zooming is working better than in the current develope branch, but when I test this locally with `npm run dev` I sometimes experiences this crash:
> 
> Yes, @norbert, there are some known issues with the zoom-in functionality. Once this PR is merged, we will work on resolving these issues. Regarding the crash, is it specific to this PR, or can it be reproduced on the develop branch as well?

I cannot reproduce the crash on the develop branch.

**Review by mohitb35 — APPROVED** [review]

**Review by mohitb35 — APPROVED** [review]
@shyambhongle LGTM

I've made some minor refactors, take a look.

**Comment by mohitb35** [comment]
@norbertschuler I couldn't reproduce the crash you mentioned while running this locally. Was it on a specific project? Or in any specific scenario?

**Comment by norbertschuler** [comment]
> @norbertschuler I couldn't reproduce the crash you mentioned while running this locally. Was it on a specific project? Or in any specific scenario?

I can not reproduce the above crash any more with the latest version now. On Vercel it works fine for me, locally with `npm run dev` the zooming does not always work. Check the attached video. But if it works on Vercel with the builded version I am fine.

https://github.com/Plant-for-the-Planet-org/planet-webapp/assets/1532418/1fe0e807-a798-4de1-83ac-13328fa44bef

**Comment by mohitb35** [comment]
Zoom works on the built version on Vercel, or at least it works as well as the current webapp on production. I think we can get this out, and handle the zoom issues separately.

**Pull request merged**
