### PR TITLE
Feature/add giftfund

### PR DESCRIPTION
**Pull request by prachigarg19**

### CODE REVIEW

**Comment by sagararyal** [comment]
#### 📝 Changed routes:


| [**/profile/giftfund**](https://planet-webapp-ja72dqm7k-planetapp.vercel.app/profile/giftfund) |
|:-:|
|<a href="https://planet-webapp-ja72dqm7k-planetapp.vercel.app/profile/giftfund">Screenshot of /profile/giftfund</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/bMINX5OebwkjrlBlJ9oq9Kl1ua_8Ts5b-jQyNXhVQr8g0Ds-vJybvJY924KZ1qf0Wfkl8oJWNm2tDLR-zND75g.png">(view full size)</a> |







Commit 2d89406c75cbc0fd148300f4b272c89c4e0a9815 (https://planet-webapp-ja72dqm7k-planetapp.vercel.app).

**Comment by mariahosfeld** [comment]
When checking with a PlanetCash account without a GiftFund, the menu item is still visible. In such cases it needs to be hidden.

**Comment by mariahosfeld** [comment]
Functionality now works as expected.

**Review by Shreyaschorge — CHANGES_REQUESTED** [review]
Jst a minor addition.

**Comment by mariahosfeld** [comment]
Now the functionality works as expected.

**Review by Shreyaschorge — APPROVED** [review]
LGTM!

**Pull request merged**
