### PR TITLE
fix: login issue using direct link

### PR DESCRIPTION
**Pull request by sunilsabatp**
issue -> login using direct link(`dev.pp.eco/login`)
 page remain in loading state

### CODE REVIEW

**Comment by mohitb35** [comment]
These breaks the complete signup flow, the user ends up in a loop

**Comment by mariahosfeld** [comment]
When I try to signup, I am stuck in a loop

**Review by mariahosfeld — COMMENTED** [review]
Functionality works as expected.

**Review by mohitb35 — APPROVED** [review]

**Review by norbertschuler — APPROVED** [review]
`/login` works for me for this pull request.

**Pull request merged**
