### PR TITLE
refetch projects on language change

### PR DESCRIPTION
**Pull request by sarveshpro**
### changes -
- refetch projects if language is changed

### CODE REVIEW

**Review by norbertschuler — COMMENTED** [review]
- [ ] Do we need to reload the TPO profile and all its projects also on the screen https://planet-webapp-nnynvaupd-planetapp.vercel.app/t/plant-for-the-planet?

**Comment by norbertschuler** [comment]
Are there any translated projects on staging to test this feature?

**Comment by sarveshpro** [comment]
> * [ ]  Do we need to reload the TPO profile and all its projects also on the screen https://planet-webapp-nnynvaupd-planetapp.vercel.app/t/plant-for-the-planet?

I think we should.

**Comment by sarveshpro** [comment]
> Are there any translated projects on staging to test this feature?

Not that I know of. Adding translations for Yucatan on staging.

**Comment by sarveshpro** [comment]
@norbertschuler I added translations to `/planbe-forest` on staging using Lokalise

**Comment by mariahosfeld** [comment]
I tested the last deployment, and while the headlines change nicely, the language of "Read More" only changed after refreshing the page
After setting language from German to English, before refresh
grafik
After refresh
grafik

**Comment by norbertschuler** [comment]
> I tested the last deployment, and while the headlines change nicely, the language of "Read More" only changed after refreshing the page After setting language from German to English, before refresh !

The used component probably has problems. I found this issue in the repo of the used module to fix it: https://github.com/alexandersmanning/read-more-react/issues/21. (We are using very much external modules we have to deal with.)

**Comment by norbertschuler** [comment]
> > Are there any translated projects on staging to test this feature?
> 
> Not that I know of. Adding translations for Yucatan on staging.

I do not see any German translation of https://planet-webapp-q5e3121ki-planetapp.vercel.app/yucatan. Maybe if someone can explain me where to do it, I can add some myself?

**Review by norbertschuler — APPROVED** [review]
If this PR is only about being able to translate project title and description, this seems to work now. If other text from the project profile entered by the TPO should also be translated, this maybe is not yet supported:

Bildschirmfoto 2022-03-05 um 14 11 20

**Pull request merged**
