### PR TITLE
Merge branch 'main' into tenant/sateins

### PR DESCRIPTION
**Pull request by norbertschuler**
This pull request updates the custom branch `tenant/sateins` with the latest changes from the `main` branch. In order to test check out the branch and change the your tenant environment to 
```
TENANT=sateins
TENANTID=ten_510O1guS
```

to see the sateins page go to `localhost:3000/home`

### CODE REVIEW

**Review by sarveshpro — APPROVED** [review]
LGTM ✔️

**Comment by norbertschuler** [comment]
@sagararyal do we want to release this now?

**Comment by sagararyal** [comment]
can merge, just make sure to monitor the site for any errors.

**Comment by norbertschuler** [comment]
https://sat1-campaign.plant-for-the-planet.org/home and https://waldrekord.sat1.de/home look ok after deployment.

**Pull request merged**
