### PR TITLE
Handle payment status draft and status success

### PR DESCRIPTION
**Pull request by harshvitra**

### CODE REVIEW

**Comment by norbertschuler** [comment]
@harshvitra this looks like the same as https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1088 which now got merged into develop as well! Can we close it?

**Comment by harshvitra** [comment]
> @harshvitra this looks like the same as #1088 which now got merged into develop as well! Can we close it?

I am confused one of them was supposed to be for main

**Comment by norbertschuler** [comment]
> > @harshvitra this looks like the same as #1088 which now got merged into develop as well! Can we close it?
> 
> I am confused one of them was supposed to be for main

Sagar just changed the base of that other pull request to develop and merged it. It's all written there (and yes it's irritating, but probably he has overseen this PR):

image

**Comment by norbertschuler** [comment]
Let’s close this.

**Pull request closed without merging**
