### PR TITLE
Add Tenant Nitro Snow Boards

### PR DESCRIPTION
**Pull request by sagararyal**

### CODE REVIEW

**Comment by norbertschuler** [comment]
@sagararyal added custom Home screen which was missing. This new tenant only exists on production, not in our development database yet.

**Comment by sagararyal** [comment]
Thanks @norbertschuler 
https://planet-app-nitro.herokuapp.com points to Production.

**Review by norbertschuler — APPROVED** [review]
LGFM

**Comment by norbertschuler** [comment]
If you want the users of this tenants to be limited to English as a language to choose, you probably will want to approve https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/377.

**Comment by harshvitra** [comment]
I am just happy that we can add Tenants easily without much friction or much dependencies. 

Will try to simplify the process more if needed

**Pull request merged**
