### PR TITLE
Draft UI for Profile

### PR DESCRIPTION
**Pull request by harshvitra**
Updated Structure and added sidebar

- [x] Accounts feature
- [ ] Token refresh
- [ ] Sidebar features 
      - [ ] Drawer open and close on hover
      - [ ] Close below 768px
      - [ ] Close submenu of other options
  

- [ ] Login redirect when we user access private account

### CODE REVIEW

**Comment by sagararyal** [comment]
#### 📝Changed routes:


| [**/account/register-trees**](https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/account/register-trees) | [**/c/\[id\]**](https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/c/[id]) |
|:-:|:-:|
|<a href="https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/account/register-trees">Screenshot of /account/register-trees</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/QmNH7kfQW3g48lnWlRbFXanAOn_wDFVJK4DBQ_UQGcRKfqKYYxlAoTRgA8sSMBwFsFGhwjgT1t9xCikmrojQXw.png">(view full size)</a> |<a href="https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/c/[id]">Screenshot of /c/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/gRUplc0PFg5sTceBEklXVkAlnvID8biOq-OqSMpypecb9hNjjVmO0qJwPxSaXcUSpi6W6gKdzlQzMGXawzcafA.png">(view full size)</a> |



| [**/claim/\[type\]/\[code\]**](https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/claim/[type]/[code]) | [**/register-trees**](https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/register-trees) |
|:-:|:-:|
|<a href="https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/claim/[type]/[code]">Screenshot of /claim/[type]/[code]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/rbpH5mIYu8b_siFD_mfTl4wJxObJ-i4cFrOoC5XNjXhM5IyTpI8ijTDmfZK3tvaUBPmHyGrvRk5moFkuElDFLQ.png">(view full size)</a> |<a href="https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/register-trees">Screenshot of /register-trees</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/JMcRti_8dWykctnI_VR2lNsaI0lzLM3F7KixaaihUgXCCCOy2JYEIarJBHOz7OMhM1g4eZblPOSxXZlew-NG5A.png">(view full size)</a> |



| [**/t/\[id\]**](https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/t/[id]) |
|:-:|
|<a href="https://planet-webapp-gzp2hf4xi-planetapp.vercel.app/t/[id]">Screenshot of /t/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/TwiRUXEqUD3X2eZOzhl_6jq9FUqv5VDbeZFA_r6JrVnaTi1fGVRdyKDRE6AfE8ef8LNHoTc9M33r8KKUFDVxhw.png">(view full size)</a> |







Commit a8098537b608864c6f15f2c4f4df82377324c4f8 (https://planet-webapp-gzp2hf4xi-planetapp.vercel.app).

**Comment by norbertschuler** [comment]
- [ ] Disable projects menu for all other account type than TPO

**Comment by norbertschuler** [comment]
- [ ] Being able to access "Create Widget" was limited to public profiles before and showed an dialog asking the user if the profile should be made public before opening the widget creator.

**Comment by norbertschuler** [comment]
- [ ] Some screens as "Edit Profile" and "Register Trees" which had been designed to be displayed centered, do not look good if they are just shown aligned to the right border of the menu.

**Comment by norbertschuler** [comment]
- [ ] "Set target" and "Redeem" from the profile screen maybe later on can also be converted into menu items, but they would of course also do not look good the way they are currently designed as modal dialogues.
- [ ] "Register Trees" maybe could be removed to avoid redundancy.

**Pull request merged**
