### PR TITLE
Feature/max density

### PR DESCRIPTION
**Pull request by sunilsabatp**
to do : max planting density text field  for restoration project

steps: 1. log in as RO and go to project
2.create or edit the project (only restoration)
3.then go to detail analysis and fill the maximum planting density 

for Frontend view of single project visit to : /projectId to check planting density info based on condition

### CODE REVIEW

**Review by norbertschuler — APPROVED** [review]
LGFM

**Review by mariahosfeld — CHANGES_REQUESTED** [review]
MaxPlantingDensity should currently not be mandatory.

**Comment by prachigarg19** [comment]
@sunilsabatp Why is inline styling being applied at multiple places in DetailedAnalysis component?
Also, could you resolve the conflicts?
I'm not able to figure out how to view max density on the frontend. Could you guide me on the same?

**Comment by sunilsabatp** [comment]
> @sunilsabatp Why is inline styling being applied at multiple places in DetailedAnalysis component? Also, could you resolve the conflicts? I'm not able to figure out how to view max density on the frontend. Could you guide me on the same?

sure

**Comment by prachigarg19** [comment]
@sunilsabatp please look into the codefactor errors. Everything looks good to me.

**Review by prachigarg19 — APPROVED** [review]
@sunilsabatp please look into the codefactor errors. Everything else looks good to me.

**Review by mariahosfeld — CHANGES_REQUESTED** [review]
Functionality works for me, but in German the layout in the project details is broken. It does not break correctly and therefore cuts of part of the headline.
This is how it looks 
grafik
This is what it should look like
grafik

**Review by mariahosfeld — APPROVED** [review]

**Comment by mariahosfeld** [comment]
Functionality works correctly as well as the layout.

**Pull request merged**
