### PR TITLE
Fix Manage projects bugs

### LINKED ISSUE #887: Improvements in Manage projects
- [x] After saving the step 1.
two concurrent requests are made: one with scope images, one without. This can be reduced to 1 API call.

https://app-staging.plant-for-the-planet.org/app/profile/projects/proj_1mKHMKjXuJ8YHc1Fn1eRSdkj?_scope=images
https://app-staging.plant-for-the-planet.org/app/profile/projects/proj_1mKHMKjXuJ8YHc1Fn1eRSdkj

- [x] Adding picture still refreshes the page to show one picture only.
Screen Shot 2021-03-08 at 10 56 21 AM
Screen Shot 2021-03-08 at 10 56 52 AM

- [x] Validation check does not occur when project certification does not contain a pdf. (same applies for project spending) (User is not informed that the project failed to save these data.)

### PR DESCRIPTION
**Pull request by harshvitra**
Fixes #887

### CODE REVIEW

**Comment by norbertschuler** [comment]
- [ ] I can not that see the last point of the linked issue got fixed: "Validation check does not occur when project certification does not contain a pdf. (same applies for project spending) (User is not informed that the project failed to save these data.)"

I have an existing project as following:
Bildschirmfoto 2021-03-12 um 16 47 26

When I enter `1000` for the amount and click the next button ("Speichern&Weiter") not network request is done, the data is not changed and the user gets no info about it, but the app shows the user the final information about going to be reviewed:

Bildschirmfoto 2021-03-12 um 16 49 09

If the user goes back the entered amount of `1000` has vanished.

**Comment by norbertschuler** [comment]
- [ ] Found another bug: If you miss to specify any coordinates for the basic data and try to go to the next page with the button ("Speichern&Weiter"), nothing happens and no error is shown (but it's blocked due to the missing coordinates):

Bildschirmfoto 2021-03-12 um 16 55 19

**Review by norbertschuler — CHANGES_REQUESTED** [review]
Please fix issues.

**Comment by sagararyal** [comment]
@harshvitra updates on the map issue?

**Pull request merged**
