### PR TITLE
Feature/typescript project prop context

### PR DESCRIPTION
**Pull request by sunilsabatp**
typescript for projectPropContext

### CODE REVIEW

**Comment by sunilsabatp** [comment]
mistakenly created pr

**Comment by sunilsabatp** [comment]
I mistakenly worked and pushed this pr , which already been closed by @mohit [#1653]

**Comment by mohitb35** [comment]
@sunilsabatp Please delete the branch /Feature/typescript_projectPropContext on local as well as remote, and move the changes made here to the branch feature/typescript_projectPropContext.

**Comment by sunilsabatp** [comment]
duplicate pr

**Pull request closed without merging**
