### PR TITLE
Tenant/andalucia

### PR DESCRIPTION
**Pull request by norbertschuler**
- I rebased the old `tenant/andalusia` branch on main and solved all the merge conflicts as good as possible. 
- This branch could be used as a new version for our tenant andalucia by just changing the deployment branch on Netlify to `tenant/andalucia`.
- You can check it out and test with these variables in your `.env.local`:
```
TENANT=andalucia
TENANTID=ten_buYCpiPN
```

This tenant is only using Spanish language without a fallback to English, so there are still some resources missing where we display the resource name instead as we have 50 unconfirmed Spanish translation resources at LingoHub, e.g.
- https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1120#issuecomment-864528363
- https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1120#issuecomment-864528881

Bildschirmfoto 2021-06-20 um 12 10 32

### CODE REVIEW

**Comment by norbertschuler** [comment]
Also upgraded with the latest bugfix, but the currently deployed version is soo old it does not contain the bug ;-)

**Comment by norbertschuler** [comment]
- [ ] resource is missing (also on https://andalucia.plant-for-the-planet.org/)

Bildschirmfoto 2021-06-20 um 11 53 32

**Comment by norbertschuler** [comment]
- [ ] menu got a different translation as on https://andalucia.plant-for-the-planet.org/ - use `Sobre nosotros` or `Acerca de`?
 
Bildschirmfoto 2021-06-20 um 11 56 39

Bildschirmfoto 2021-06-20 um 11 53 39

**Comment by norbertschuler** [comment]
- [ ] `status` in footer should begin with uppercase character as the other items:

Bildschirmfoto 2021-06-20 um 11 57 34

**Comment by norbertschuler** [comment]
If we merge the export of the machine translated resources in https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1144, we could update this branch as well.

**Comment by norbertschuler** [comment]
I will update the tenant branch once #1157 got released.

**Comment by sagararyal** [comment]
#### 📝Changed routes:


| [**/andoalcala**](https://planet-webapp-kf67her85-planetapp.vercel.app/andoalcala) | [**/andodonana**](https://planet-webapp-kf67her85-planetapp.vercel.app/andodonana) |
|:-:|:-:|
|<a href="https://planet-webapp-kf67her85-planetapp.vercel.app/andoalcala">Screenshot of /andoalcala</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/vhNCFjr1d6GXwyf4Rxj_saw-wcyD4xfeiBrod4-j6L6_TsKQFTQ7G2Wj6NVueHfuc6b5pprviyL9Rq3H1CABxA.png">(view full size)</a> |<a href="https://planet-webapp-kf67her85-planetapp.vercel.app/andodonana">Screenshot of /andodonana</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/69lArQLJG1KgWG5nqJJZwMrVPkmn5501_TW86wvNSpU3zp9Hem4Z6_4W46d7VCUXlelBRKKtx-sBsGuUcwJVzQ.png">(view full size)</a> |



| [**/granada**](https://planet-webapp-kf67her85-planetapp.vercel.app/granada) |
|:-:|
|<a href="https://planet-webapp-kf67her85-planetapp.vercel.app/granada">Screenshot of /granada</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/E1209HF7BS-FTFIMK1ZM1UtuG_n_lszUmCb6JuZrLxa-S6RShESu-EiN_q1DKEBLppNKLwdN-VQrqgAbt3kK_A.png">(view full size)</a> |







Commit e1c6193bc6b7bf88bde65491fd6f41f64b211f97 (https://planet-webapp-kf67her85-planetapp.vercel.app).

**Comment by norbertschuler** [comment]
Finally updated this branch. So we can close this PR now (keep the branch).

**Pull request closed without merging**
