### PR TITLE
Feature/country selector

### LINKED ISSUE #530: Replace country codes in country selector with currency code
Please check Edit Profile, Signup, Donate and Project forms.
Screen Shot 2020-12-02 at 10 56 49 AM

### PR DESCRIPTION
**Pull request by captainamiedi**
Fixes #530 

Changes in this pull request:
- Replace country codes in country selector with currency code
-
-

@sagararyal

### CODE REVIEW

**Comment by norbertschuler** [comment]
@captainamiedi you branched this from `feature/reactAuth0` but based this PR on `develop`. That's not a good idea. I suggest you rebase (`git rebase develop`) your branch to be based on the `develop` branch.

**Comment by captainamiedi** [comment]
> @captainamiedi you branched this from `feature/reactAuth0` but based this PR on `develop`. That's not a good idea. I suggest you rebase (`git rebase develop`) your branch to be based on the `develop` branch.

@sagararyal suggested i base of `feature/reactAuth0`. i think these is to reduce merge conflict when `feature/reactAuth0` is merged. since `feature/reactAuth0` has a lot of changes

**Comment by norbertschuler** [comment]
- [ ] This adds the currency name also to the country selection list when editing a user profile which probably is not intended, but only for entering an address in the donation form, is it?

Bildschirmfoto 2020-12-02 um 16 52 30

As I wrote in https://github.com/Plant-for-the-Planet-org/planet-webapp/issues/530#issuecomment-737143959 I do not think we should show the currency next to the country as people might want to pay with other currencies as the one proposed for a certain country and can be irritated otherwise.

**Comment by norbertschuler** [comment]
@sagararyal I won't approve this until my question at https://github.com/Plant-for-the-Planet-org/planet-webapp/issues/530#issuecomment-737143959 is clarified :-)

**Pull request closed without merging**
