### PR TITLE
Input field css in contact details

### PR DESCRIPTION
**Pull request by rishsingh07**
After error the input field used to get widen.

### CODE REVIEW

**Review by harshvitra — APPROVED** [review]

**Comment by norbertschuler** [comment]
@rishsingh07 please fix error from `npm run lint:errors` to let us try to have clean code:

```
/home/runner/work/planet-webapp/planet-webapp/src/features/user/UserProfile/components/MyTrees/MyTrees.tsx
  78:21  error  'date' is never reassigned. Use 'const' instead  prefer-const
```

**Comment by norbertschuler** [comment]
> @rishsingh07 please fix error from `npm run lint:errors` to let us try to have clean code:
> 
> ```
> /home/runner/work/planet-webapp/planet-webapp/src/features/user/UserProfile/components/MyTrees/MyTrees.tsx
>   78:21  error  'date' is never reassigned. Use 'const' instead  prefer-const
> ```

Actually this file was wrong before. Let's not fix this in this PR, but in another. It's not related to your code changes.

**Comment by rishsingh07** [comment]
image

**Comment by rishsingh07** [comment]
Now :

**Comment by rishsingh07** [comment]
Now -
image

earlier-
image
image

**Pull request merged**
